### ISSUE TITLE
无法安装lz4

### ISSUE THREAD

**Issue by q2529608758** [kvarenzn/phisap#10]
E:\sudo板子自己打歌>pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting lz4==3.1.10
  Downloading lz4-3.1.10.tar.gz (162 kB)
     |████████████████████████████████| 162 kB 312 kB/s
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy==1.21.4 in c:\users\450safe\appdata\roaming\python\python310\site-packages (from -r requirements.txt (line 2)) (1.21.4)
Using legacy 'setup.py install' for lz4, since package 'wheel' is not installed.
Installing collected packages: lz4
    Running setup.py install for lz4 ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\450Safe\\AppData\\Local\\Temp\\pip-install-iv_ww8cr\\lz4_70a5d7f6a5fc446a9996e3efafc3028f\\setup.py'"'"'; __file__='"'"'C:\\Users\\450Safe\\AppData\\Local\\Temp\\pip-install-iv_ww8cr\\lz4_70a5d7f6a5fc446a9996e3efafc3028f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\450Safe\AppData\Local\Temp\pip-record-20fpskiv\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\450Safe\AppData\Roaming\Python\Python310\Include\lz4'
         cwd: C:\Users\450Safe\AppData\Local\Temp\pip-install-iv_ww8cr\lz4_70a5d7f6a5fc446a9996e3efafc3028f\
    Complete output (22 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\lz4
    copying lz4\version.py -> build\lib.win-amd64-3.10\lz4
    copying lz4\__init__.py -> build\lib.win-amd64-3.10\lz4
    creating build\lib.win-amd64-3.10\lz4\block
    copying lz4\block\__init__.py -> build\lib.win-amd64-3.10\lz4\block
    creating build\lib.win-amd64-3.10\lz4\frame
    copying lz4\frame\__init__.py -> build\lib.win-amd64-3.10\lz4\frame
    creating build\lib.win-amd64-3.10\lz4\stream
    copying lz4\stream\__init__.py -> build\lib.win-amd64-3.10\lz4\stream
    running build_ext
    building 'lz4._version' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\450Safe\\AppData\\Local\\Temp\\pip-install-iv_ww8cr\\lz4_70a5d7f6a5fc446a9996e3efafc3028f\\setup.py'"'"'; __file__='"'"'C:\\Users\\450Safe\\AppData\\Local\\Temp\\pip-install-iv_ww8cr\\lz4_70a5d7f6a5fc446a9996e3efafc3028f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\450Safe\AppData\Local\Temp\pip-record-20fpskiv\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\450Safe\AppData\Roaming\Python\Python310\Include\lz4' Check the logs for full command output.

**Comment by kvarenzn** [comment]
您好，报错这里
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

已经说明问题原因了，是因为您没有安装"Microsoft C++ Build Tools"，请安装后再重新`pip install -r requirements.txt`。至于如何安装"Microsoft C++ Build Tools"，烦请您百度搜索。
