### ISSUE TITLE
运行main.py时报错 SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by pylazy-chara** [kvarenzn/phisap#100]
adb可以使用，server也放在根目录下
main.py没有经过改动且库全都装好
![QQ截图20230801224014](https://github.com/kvarenzn/phisap/assets/75147543/9f2ed5a7-ca8e-46f2-8347-d8717518e075)

**Comment by ghost** [comment]
这边我自己下了下最新版，啥也没动也能打开，看这个报错提示我猜应该是你Python版本错了，注意如果安装了多个Python版本记得检查启动Phisap的版本正不正确

**Comment by pylazy-chara** [comment]
> 
tks 我装了3.7 3.9 3.10 3.11
卸载完就好了
但是File "C:\Users\Alienware\Desktop\phisap\main.py", line 684, in autoplay
    assert self.controller is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
又是怎么一回事😭

**Comment by ghost** [comment]
进程残留？重启下电脑也许行吧）这个我就不知道了

**Comment by ghost** [comment]
如果不行试试重新下载Phisap

**Comment by pylazy-chara** [comment]
> 如果不行试试重新下载Phisap

都试过了 没用
第三个lssue也是这个问题（

**Comment by pylazy-chara** [comment]
> 如果不行试试重新下载Phisap

我好像找到问题了
phisap找不到我的设备

**Comment by ghost** [comment]
下次放个截图（

> phisap找不到我的设备

应该是adb的问题吧

**Comment by ghost** [comment]
#99 也行是adb环境配置的问题？

**Comment by pylazy-chara** [comment]
> #99 也行是adb环境配置的问题？

#97

**Comment by pylazy-chara** [comment]
> 下次放个截图（
> 
> > phisap找不到我的设备
> 
> 应该是adb的问题吧

![屏幕截图 2023-08-02 120324](https://github.com/kvarenzn/phisap/assets/75147543/83c2210e-8bde-4bdc-9aad-a036b4ef846a)

**Comment by ghost** [comment]
是
![Snipaste_2023-08-02_12-05-37](https://github.com/kvarenzn/phisap/assets/129530250/1b7558c9-3286-47f9-bf89-2e0f4c8fec0f)
这里点刷新没有设备吗

**Comment by pylazy-chara** [comment]
是的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月2日(周三) 中午12:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [kvarenzn/phisap] 运行main.py时报错 SyntaxError: invalid syntax (Issue #100)




 
是
 
 这里点刷新没有设备吗

**Comment by ghost** [comment]
https://github.com/kvarenzn/phisap/issues/97 这个谱面规划问题我没办法，只能等作者修复

**Comment by ghost** [comment]
> 是的

你可以尝试把下载的adb放入Phisap根文件夹里，我就这样做的，没有adb的问题

**Comment by pylazy-chara** [comment]
好的,待会我去试一下
谢谢啦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月2日(周三) 中午12:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [kvarenzn/phisap] 运行main.py时报错 SyntaxError: invalid syntax (Issue #100)




  
是的
  
你可以尝试把下载的adb放入Phisap根文件夹里，我就这样做的，没有adb的问题

**Comment by ghost** [comment]
另外，我现在常用的Phisap是这个https://github.com/kvarenzn/phisap/tree/82da0e85b9d982474be86a7ac672d1aa234fa122
不过我进行了小修改，之后我说明下，这个版本我目前没有遇到不能ap的歌

**Comment by pylazy-chara** [comment]
OK



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月2日(周三) 中午12:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [kvarenzn/phisap] 运行main.py时报错 SyntaxError: invalid syntax (Issue #100)




 
另外，我现在常用的Phisap是这个https://github.com/kvarenzn/phisap/tree/82da0e85b9d982474be86a7ac672d1aa234fa122
 不过我进行了小修改，之后我说明下，这个版本我目前没有遇到不能ap的歌

**Comment by pylazy-chara** [comment]
> 另外，我现在常用的Phisap是这个https://github.com/kvarenzn/phisap/tree/82da0e85b9d982474be86a7ac672d1aa234fa122 不过我进行了小修改，之后我说明下，这个版本我目前没有遇到不能ap的歌

谢谢！可以了
