### ISSUE TITLE
Phira的自制谱无法AP（Dev）

### ISSUE THREAD

**Issue by ghost** [kvarenzn/phisap#107]
大佬好捏。滑键配置是-17，17，垂直
首先呢，模拟器是Phira，我用不会[server]报错的版本 #88 ，在打Duplicity ShadeAT 17.27*的时候 #97 ，手机会严重吃音，和 #98 中的情况差不多，但是时间越长手机发热越严重，而且控制台不断传来客户端的scrcpy视频编解码的报错，最后整个手机直接卡死了，拔下USB或关闭Phisap即可恢复。（图片忘记截了，不过和 #87中图片控制台的最后两行差不多）
然后我更新了Phisap（即不用OMX.google.h264.encoder的版本），上述情况就消失了，不过会重复报一下错误，但不会影响打歌
![Snipaste_2023-08-06_07-50-03](https://github.com/kvarenzn/phisap/assets/129530250/20608699-becd-410a-8324-606011e20724)
另外，我下载了最新Dev版Phisap，把algo2的算法修改了下面图片这一项，
![Snipaste_2023-08-06_08-08-44](https://github.com/kvarenzn/phisap/assets/129530250/129a4073-2fcd-47c3-8f6d-dbc47989d810)
这样做在Phira里仍然不能ap，于是我换了个模拟器
![Screenshot_2023-08-06-07-49-03-98_69fcb1c0115127b512b6c7c2cc7c4c1b](https://github.com/kvarenzn/phisap/assets/129530250/b1ecac2c-7dc4-40ee-a86c-4eca9bce23d1)
啊就能ap了
震惊.jpg
~因此目前Phisap激进算法应该没有问题，只是规划错了吗~
所以自制谱能不能ap应该还取决于模拟器，（建议readme.md里说明一下？）

**Comment by ghost** [comment]
ap的模拟器是Re:Phigros

**Comment by kvarenzn** [comment]
> 另外，我下载了最新Dev版Phisap，把algo2的算法修改了下面图片这一项，

分配不了指针就直接跳过还行，你这也太暴力了吧
这招可能对这首有用，但对其他曲目还真不好说
不过也确实是个思路，我之后会给algo2加个设置项

> 这样做在Phira里仍然不能ap，于是我换了个模拟器

我说怎么今天一觉起来掉到榜二了，原来榜一事你（
昨天我用刚写好的algo3测试了一下，能规划，回测也正常，但在phira里确实就是老miss，所以没准还真是模拟器的问题？特别是粉键，据说RPE的粉键判定比较宽松？具体的就不知道了（我没进群，也没法测试
不过能AP就好

**Comment by ghost** [comment]
> 分配不了指针就直接跳过还行，你这也太暴力了吧

我也不知道为啥ap了233


> 我说怎么今天一觉起来掉到榜二了，原来榜一事你（

我说怎么今天一觉起来谁把tc干了，原来是你（

> 但在phira里确实就是老miss

我的就是在7k尾杀疯狂miss，全是蓝键也miss，所以我猜模拟器吃音了

> 特别是粉键，据说RPE的粉键判定比较宽松？具体的就不知道了

这个谱本来没有多少红键，且Phiramiss的都不是红键，但据说非常稳定，手感很好

**Comment by ghost** [comment]
确定了是Phira吃音，参考未上架的分类中纯配置的“volcanic (full version)”,这个谱全蓝键，在谱面流速十分快的时候会一直miss

**Comment by kvarenzn** [comment]
> 参考未上架的分类中纯配置的“volcanic (full version)”,这个谱全蓝键

虽然但是，你说的这个谱我没找到（
感觉phira的搜索功能跟废了没啥区别

**Comment by ghost** [comment]
可以不搜全称

**Comment by ghost** [comment]
![Screenshot_2023-08-06-10-36-00-70_d2f71cd433eba6fe82c4c12ffba30ed5](https://github.com/kvarenzn/phisap/assets/129530250/94aaf149-33a0-4cde-910f-d147bc9e057f)

**Comment by kvarenzn** [comment]
多谢

**Comment by kvarenzn** [comment]
试了一下，确实，我这边最好成绩是两个miss，用的是极端算法
但是不是吃音还真不好说，毕竟现在也确实没有真人能AP

**Comment by 364hao** [comment]
那啥，试了试0.15
![Screenshot_2023-08-06-12-34-52-44_d2f71cd433eba6fe82c4c12ffba30ed5](https://github.com/kvarenzn/phisap/assets/129530250/5f56ade5-10e1-4cd8-a39a-7906c7f574cd)

https://github.com/kvarenzn/phisap/assets/129530250/4fdc8cb5-8126-4803-8cc3-4b7bccaabd95

这个是极端算法

**Comment by 364hao** [comment]
另外那个激进算法新更新的功能，和algo3好像都规划不了这个谱面INTERNET YAMERO
![Screenshot_2023-08-06-13-02-58-00_d2f71cd433eba6fe82c4c12ffba30ed5](https://github.com/kvarenzn/phisap/assets/129530250/9b766076-3256-452c-b288-cc6255ba10ed)

**Comment by ghost** [comment]
不过对于新算法，这么短的时间能做出这样效果十分不错(≧▽≦)

**Comment by kvarenzn** [comment]
> 另外那个激进算法新更新的功能，和algo3好像都规划不了这个谱面INTERNET YAMERO

OK，我看看

**Comment by ghost** [comment]
![Screenshot_2023-08-06-15-48-21-65_69fcb1c0115127b512b6c7c2cc7c4c1b](https://github.com/kvarenzn/phisap/assets/129530250/83bddd0e-9f89-4559-bee3-8c6c20896e3e)
好吧能不能ap只能抽奖

**Comment by 364hao** [comment]
![Screenshot_2023-08-06-15-39-20-81_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/kvarenzn/phisap/assets/129530250/8ac1f943-a907-46d9-b8b9-af8743c75144)
这个是另一个模拟器，爆发段好像吃了

**Comment by 364hao** [comment]
![Screenshot_2023-08-06-19-06-56-15_149003a2d400f6adb210d7e357a3a646](https://github.com/kvarenzn/phisap/assets/129530250/3fa8362e-9538-4f3f-be83-675b95c9a5ec)
草

**Comment by kvarenzn** [comment]
打得好就是开了？开了就是挂？bu就是见不得人好

**Comment by ghost** [comment]
那啥
![Snipaste_2023-08-07_08-39-41](https://github.com/kvarenzn/phisap/assets/129530250/745f1061-5520-474b-ab3b-a270f969c4f5)
![Snipaste_2023-08-07_08-40-50](https://github.com/kvarenzn/phisap/assets/129530250/47c9363c-5b6e-4f05-b534-48f982bb01ab)
这个按钮的意思应该是所有note规划失败都这样吧.png

**Comment by kvarenzn** [comment]
理论上是这样的，不过要是连flick跟tap都漏的话，那说明彻底寄了，还不如换个算法试试

**Comment by ghost** [comment]
Phira里有调整谱面速度的设置，可以试试把流速调慢后会不会miss，但调了这个整个谱就变速了，各个note击打时间就不一致了，所以作者有考虑支持这一项功能吗

**Comment by ghost** [comment]
可以验证下是不是模拟器的问题

**Comment by kvarenzn** [comment]
这下破案了
![Screenshot_20230808-140632](https://github.com/kvarenzn/phisap/assets/12197126/9eaccc1e-eeab-432d-a5ea-fc69af5eacff)

**Comment by kvarenzn** [comment]
确实漏判

**Comment by ghost** [comment]
应该是的，我怎么刷也刷不上去
（不过你怎么做到Acc99.85的）
我开了触点看了下，感觉algo3有时把tap+drag的键型组合按两下，不太确定
另外PEC谱面的功能会不会支持stable啊，我想试试旧版的algo1，2

**Comment by ghost** [comment]
等会我没看到更新让我再试试

**Comment by kvarenzn** [comment]
> （不过你怎么做到Acc99.85的）

这个值算是低还是高？

> 另外PEC谱面的功能会不会支持stable啊，我想试试旧版的algo1，2

不能捏，如果支持了就变成dev了，新版的algo1和2跟旧版的没什么差别

**Comment by kvarenzn** [comment]
你说的Acc不会是指“无瑕度”吧，phisap本来就可以做到很强的无瑕度，之前玩<del>Idol IN</del>甚至可以达成<=5ms的误差
(忘了是哪首了，刚才看了一眼不是Idol，那就有可能是吉他与孤独与蓝色星球？phira更新后之前下载过的歌曲全特么没了）
你是不是没有用过“微调”功能？

**Comment by ghost** [comment]
我其实意思是两个都有，都好奇你acc和无暇度怎么这么高，acc高是miss的少吧，无暇度应该就是我调过微调但是这个谱不能做到100%调完后与判定线契合，但大多数情况我不怎么管这个，这个谱我会提前一些防止漏判啥的

还有我真的用过微调啊啊啊 

> 这个值算是低还是高？

高，主要是漏的少吧，因为看你acc高但是分少推测在中间的时候断了

> 新版的algo1和2跟旧版的没什么差别

也是哦，新版修复bug后还没测试能不能ap之前不能ap的谱了

![Screenshot_2023-08-08-15-13-25-33_d2f71cd433eba6fe82c4c12ffba30ed5](https://github.com/kvarenzn/phisap/assets/129530250/951af44d-7157-4282-9c2e-a7e5fea6b0c5)

（0.5x为什么还能miss）

**Comment by ghost** [comment]
> phira更新后之前下载过的歌曲全特么没了

我记得可以用adb保留数据升级降级软件的，实在不行可以试试adb backup备份看看

**Comment by ghost** [comment]
> 不能捏，如果支持了就变成dev了，新版的algo1和2跟旧版的没什么差别

主要是旧版从未遇过不能ap的曲子，但自己接入pec谱面时谱面的共有信息又修改太多了，改起来很麻烦（其实是我懒.jpg

**Comment by kvarenzn** [comment]
> 我记得可以用adb保留数据升级降级软件的，实在不行可以试试adb backup备份看看

这个是phira自己的bug，原来下载的谱面都在，但就是显示不出来（用搜索能搜出来，然后可以直接打，不用再次下载）

> 因为看你acc高但是分少推测在中间的时候断了

还真是，开始的时候断了一次，中间没断过，在最后1/5的位置差不多又断了几次

> （0.5x为什么还能miss）

应该还是漏判了，这个谱子即使0.5倍也有一段note下落特别频繁，我的3个miss都是在那块miss的

> 但自己接入pec谱面时谱面的共有信息又修改太多了，改起来很麻烦

没懂，详细说说？

**Comment by ghost** [comment]
[https://github.com/kvarenzn/phisap/commit/82da0e85b9d982474be86a7ac672d1aa234fa122](url)
就我用的旧版是这个，为了适配触控率我改了几个hold和flick的判定，但这个版本旧了，我在commits里能找的到的最低支持pec的版本是v0.4，我照着上面“为了适配触控率我改了几个hold和flick的判定”改了后记得RrAT好像ap不了就放弃用这个版本的想法，但这时候algo和algo_base文件都大改了，加入了basis.py，我记得后来还有bamboo.py（说实话我现在除了知道这两个文件似乎是算法的依赖文件外完全不知道是干啥的）把它迁移回去特别棘手就放弃了

**Comment by ghost** [comment]
> 还真是，开始的时候断了一次，中间没断过，在最后1/5的位置差不多又断了几次

另外你测试的算法是algo3吗，为啥我这边的algo3只能打S等级）

**Comment by kvarenzn** [comment]
> 加入了basis.py，我记得后来还有bamboo.py（说实话我现在除了知道这两个文件似乎是算法的依赖文件外完全不知道是干啥的）

`basis.py`这个文件里就是一些共用的抽象类定义，里边没有任何的逻辑相关代码
`bamboo.py`这个文件实现的是各种Events相关的类和处理函数。我管这玩意叫“时间线”，因为一个事件的定义通常是“在时间点A到时间点B，值x由a以某种方式变为b”，这些事件按照先后顺序在时间轴上线性排列，像是一节一节的竹子，所以叫bamboo（）。这个文件是用来快速计算在某个时间点判定线的各种属性的，比如坐标、倾角、透明度等等

> 另外你测试的算法是algo3吗，为啥我这边的algo3只能打S等级）

确实是algo3，我这边用algo3也只能打到S啊（正常速度），0.5倍就是3good 3miss

**Comment by ghost** [comment]
> 确实是algo3，我这边用algo3也只能打到S啊（正常速度），0.5倍就是3good 3miss

可我是920000诶

**Comment by kvarenzn** [comment]
> 可我是920000诶

是最新版吗？如果是的话那还蛮奇怪的（

**Comment by ghost** [comment]
> 这些事件按照先后顺序在时间轴上线性排列，像是一节一节的竹子，所以叫bamboo（）。
> 
> > 

太LeaF了

**Comment by ghost** [comment]
> 是最新版吗？如果是的话那还蛮奇怪的（

是的

**Comment by kvarenzn** [comment]
刚试了一下，951735
话说你92w是几个miss？

**Comment by ghost** [comment]
![Screenshot_2023-08-08-16-49-43-23_d2f71cd433eba6fe82c4c12ffba30ed5](https://github.com/kvarenzn/phisap/assets/129530250/7d0fc0ed-1021-481d-a071-4ecfb55e393c)

**Comment by ghost** [comment]
不过为什么algo2在接长条的时候没有触点在屏幕上，algo3却一直有呢

**Comment by kvarenzn** [comment]
> 不过为什么algo2在接长条的时候没有触点在屏幕上，algo3却一直有呢

最佳答案：我不知道.jpg
谁知道phira咋实现的，而且我是真不想细看rust代码，满篇鬼画符

**Comment by ghost** [comment]
所以algo3为什么这个蓝键会掉
![IMG_20230808_170836](https://github.com/kvarenzn/phisap/assets/129530250/c295cd72-8868-49e1-bdb4-c4789d8d2475)

**Comment by ghost** [comment]
> 谁知道phira咋实现的，而且我是真不想细看rust代码，满篇鬼画符

原来是phira的问题吗，我还以为是算法的不同

**Comment by kvarenzn** [comment]
> 原来是phira的问题吗，我还以为是算法的不同

这俩算法接长条时唯一的区别就是algo2会每1毫秒发送一次MOVE事件，algo3每8毫秒发送一次MOVE事件

> 所以algo3为什么这个蓝键会掉

我还真没遇到过，我miss的地方不在这，而且miss的基本都是红键

**Comment by ghost** [comment]
啊这，我把algo3算法的采样率改为1000就连上了

**Comment by ghost** [comment]
原来采样率也能影响蓝键的吗

**Comment by kvarenzn** [comment]
> 啊这，我把algo3算法的采样率改为1000就连上了

啊？你咋改的

> 原来采样率也能影响蓝键的吗

都是玄学

**Comment by ghost** [comment]
因为整个文件就这一个125所以我就改了（
![Snipaste_2023-08-08_18-02-34](https://github.com/kvarenzn/phisap/assets/129530250/321561a5-d569-4424-8606-1d1f4233f7fe)

**Comment by ghost** [comment]
> 都是玄学

但是不知道为什么这个地方老是掉
![Snipaste_2023-08-08_18-06-28](https://github.com/kvarenzn/phisap/assets/129530250/758c7b0e-a4ab-49ec-936d-f6b9c482ad67)

**Comment by kvarenzn** [comment]
> 因为整个文件就这一个125所以我就改了（

虽然但是，你改错了
![2023-08-08-181827_408x85_scrot](https://github.com/kvarenzn/phisap/assets/12197126/db479536-844f-456e-9935-015233740e0e)
这三行都要改

改完应该是
```python
ms2ts = lambda ms: ms
ts2ms = lambda ts: ts
ts2s = lambda ts: ts / 1000
```
否则按照你的方法改，改完后采样率仍然是125Hz

**Comment by kvarenzn** [comment]
`>> 3`等同于`/ 8`，`<< 3`等同于`* 8`

**Comment by 364hao** [comment]
az

**Comment by ghost** [comment]
坏了我位运算白学了

**Comment by ghost** [comment]
不推了，怎么也上不去，先这样吧

**Comment by ghost** [comment]
![Screenshot_2023-08-08-22-35-25-50_d2f71cd433eba6fe82c4c12ffba30ed5](https://github.com/kvarenzn/phisap/assets/129530250/81df4c2a-ad61-4c3a-a145-8ae259e63342)
憋憋

**Comment by ghost** [comment]
> 好吧能不能ap只能抽奖

不，不是抽奖，在REP里[https://github.com/kvarenzn/phisap/commit/b0496a580e9e7db4a4401de5739d3aabff53f6dc](url)这个commit是100%AP的
