### ISSUE TITLE
模拟触控标记

### ISSUE THREAD

**Issue by sjfhsjfh** [kvarenzn/phisap#108]
是否可以通过刻意设计使模拟触控与真实触控有明显差异的特征，并且不影响功能(可以参考已有的一些Arcaea ai)
意在方便客户端识别避免排行榜作弊

**Comment by kvarenzn** [comment]
虽然但是，phisap**就是**一个外挂
你让一个外挂来故意被客户端识别，这是否有点...

**Comment by yinlinghunjiang** [comment]
什么杀软东西，难蚌

**Comment by sjfhsjfh** [comment]
虽然close了, 但还是忍不住说一句, 我是以善意假定原则在推测此项目可能出于技术目的建立
个人认为避免作弊成绩上榜是愿意维护良好游戏环境的玩家的共识
如果该仓库开发者的目的即为作弊, 可以无视这一条, 权当我是跳梁小丑好了

计划在近期针对该仓库进行反作弊识别

**Comment by kvarenzn** [comment]
> 虽然close了, 但还是忍不住说一句, 我是以善意假定原则在推测此项目可能出于技术目的建立

你还是忍住好了，没人想听你搁这指点
那我权当你是来找茬的好了，慢走不送

> 计划在近期针对该仓库进行反作弊识别

那我觉得你应该先把反作弊识别的代码写出来再逼逼

**Comment by yinlinghunjiang** [comment]
yyw 是这样的

**Comment by kvarenzn** [comment]
> yyw 是这样的

你是?
