### ISSUE TITLE
无法按下按键

### ISSUE THREAD

**Issue by 114514enenenaaaaaa** [kvarenzn/phisap#109]
服务器一直报错：
[server] WARN: Ignore touch event, it was generated for a different device size

**Comment by 114514enenenaaaaaa** [comment]
![image](https://github.com/kvarenzn/phisap/assets/117449149/7ac1f61c-57c1-4cfa-88d8-ed8790009bff)
系统版本 11 23H2 Beta
adb版本1.0.41
python 3.11
手机PCAM10（OPPOA9）
主要原因：无法触控
大量输出相同日志：
[server] WARN: Ignore touch event, it was generated for a different device size

**Comment by kvarenzn** [comment]
请问有尝试过直接使用scrcpy吗？能否正常工作？
无论正常工作与否，都请发一下scrcpy在终端的输出

**Comment by 114514enenenaaaaaa** [comment]
已解决，需要手动调整手机分辨率

**Comment by kvarenzn** [comment]
> 已解决，需要手动调整手机分辨率

如果解决了这边建议点一下"Close with comment"
