### ISSUE TITLE
按下开始后无任何反应

### ISSUE THREAD

**Issue by 45231hgjkl** [kvarenzn/phisap#11]
主文件的UI可以打开并能解包APK，经过测试ADB和scrcpy都可以正常运行，在按下开始后两种方式都不会产生触摸反馈

**Comment by kvarenzn** [comment]
您好，这算是ui设计失误。在按下开始按钮后一段时间内程序会先规划谱面，看起来像卡死一样。这段时长由选择的谱面和规划算法而定，从10秒至1分钟不等。**请您在点击开始后耐心等待。** 在（规划完毕后）下次游玩相同的谱面时为了节省时间请选择规划算法为「不规划」。

**Comment by kvarenzn** [comment]
另外由于我正在设计并编写新的程序界面，故现在的这版ui不再进行改动，如有使用上的不便，敬请多多包涵

**Comment by 45231hgjkl** [comment]
我觉得不是UI的问题，我在按下开始后终端输出已经规划完毕，但是依然不会产生触摸行为

**Comment by kvarenzn** [comment]
啊这，确实很奇怪。请问方便提供一下手机的系统版本、adb版本等相关信息吗，以便于我有空时进行错误排查

**Comment by 45231hgjkl** [comment]
adb版本1.0.41
![IMG_20220206_134538](https://user-images.githubusercontent.com/14247769/152669303-8d3660f3-f2e5-4afd-acac-86fbcd3bcae5.jpg)

**Comment by kvarenzn** [comment]
ok多谢

**Comment by 45231hgjkl** [comment]
> 

https://user-images.githubusercontent.com/14247769/152687881-9a2a6af4-8d43-49aa-81cc-b0319d7ef77f.mp4

这是做的一个测试的录屏（右侧的同屏只是为了展示移动端的情况，在关闭后问题依然存在，所以不应该是adb的占用问题），可供参考

**Comment by kvarenzn** [comment]
您传的视频我看了，您可以尝试一下：**将scrcpy-server重命名为scrcpy-server-v1.21**，然后再重试一次。
另外，当您选择“延时同步”时，您不需要手动点击重试按钮，程序会自动完成这一步。

**Comment by kvarenzn** [comment]
您传的视频我看了，您可以尝试一下：**将scrcpy-server重命名为scrcpy-server-v1.21**，然后再重试一次。
另外，当您选择“延时同步”时，您不需要手动点击重试按钮，程序会自动完成这一步。

**Comment by kvarenzn** [comment]
您传的视频我看了，您可以尝试一下：**将scrcpy-server重命名为scrcpy-server-v1.21**，然后再重试一次。
另外，当您选择“延时同步”时，您不需要手动点击重试按钮，程序会自动完成这一步。

**Comment by 45231hgjkl** [comment]
![Screenshot_2022-02-07-20-39-14-979_com PigeonGames Phigros](https://user-images.githubusercontent.com/14247769/152791740-14b58fc7-e941-428a-9c55-4b8cf95c5c48.jpg)
好了，已经解决了，顺带附上大好人对截图

**Comment by kvarenzn** [comment]
草，这里建议您进行一个计时器同步的设置（程序没法自动与游戏同步，见谅）
