### ISSUE TITLE
在使用最新版本后找不到设备

### ISSUE THREAD

**Issue by huangacid** [kvarenzn/phisap#114]
**声明**
- [x] 在提问前，我已经完整地阅读并理解了README.md的内容
- [ ] 我在Issues中搜索过，确保没有其他人提过类似的问题
**如何复现**
复现此问题的步骤:
运行python  .main.py,.发现未发现设备，点击刷新就出现这个问题

**预期行为**
能使用

**截图**
![image](https://github.com/kvarenzn/phisap/assets/132374589/c922d250-013e-4902-a341-e563afda51ac)

**桌面端信息(请补充以下信息):**
 - 操作系统及其版本: windows 11
 - 使用的phisap分支: dev
 - 使用的phisap版本: 0.18

**游戏设备信息(请补充以下信息):**
 - 设备型号: 华为matepad10.4
 - 系统版本:鸿蒙3

**附加信息**
请在此补充任何其他的你认为必要的信息。

**Comment by kvarenzn** [comment]
（可能）已修复，请更新后验证

**Comment by huangacid** [comment]
目前看来可以使用，点击刷新后会有设备出现但是，不知道为什么再点一回刷新就会未响应

**Comment by ghost** [comment]
> 点击刷新后会有设备出现但是，不知道为什么再点一回刷新就会未响应

一样的问题， 之前貌似就有了 #84

**Comment by kvarenzn** [comment]
经过我这段时间的测试，OTG的稳定性要远高于scrcpy-server的稳定性，所以以后的版本将废弃掉以scrcpy-server作为后端的功能

**Comment by ZiHengPlazy** [comment]
同样的问题
![捕获](https://github.com/kvarenzn/phisap/assets/111084640/27cea1a5-b554-41db-ac19-aa000da78b7e)

**Comment by ghost** [comment]
最新版是有这样的问题，请尝试scrcpy
![Clip_2024-02-07_20-56-48](https://github.com/kvarenzn/phisap/assets/129530250/f1436ad1-15ab-49dd-8b18-60bb8ee6df79)
