### ISSUE TITLE
你说得对但是dev分支最新版无法打开

### ISSUE THREAD

**Issue by zzy6011** [kvarenzn/phisap#115]
**声明**
_确保你在提问前做到了下面两项，每当完成了一项，请在对应的中括号`[]`内敲入一个`x`，即`[x]`_
- [x] 在提问前，我已经完整地阅读并理解了README.md的内容
- [ ] 我在Issues中搜索过，确保没有其他人提过类似的问题

**描述问题**
你说得对但是dev分支的不能用

**如何复现**
复现此问题的步骤:
按照readme里的步骤，安装python3.11，配置adb，安装依赖，下载scrcpy文件，然后打开报错

**预期行为**
正常运行

**截图**
![image](https://github.com/kvarenzn/phisap/assets/117558117/3ca58dfb-f282-4565-a31e-7e78b0a7a3bf)
![image](https://github.com/kvarenzn/phisap/assets/117558117/f70aed68-46ee-4fd3-9d9c-f2e033ccc2e9)

**桌面端信息(请补充以下信息):**
 - 操作系统及其版本: windows10 22H2
 - 使用的phisap分支: dev分支
 - 使用的phisap版本: 最新版v0.19

**游戏设备信息(请补充以下信息):**
 - 设备型号: [例如: OnePlus 7 Pro]
 - 系统版本: funtouchOS_10.5
 - 安卓版本:11
 - adb版本: 1.0.41

**附加信息**
stable的都能使用

**Comment by kvarenzn** [comment]
你说的对，但是
为什么要用IDLE运行phisap？我README里写了要用命令行，使用`python main.py`运行

**Comment by zzy6011** [comment]
![image](https://github.com/kvarenzn/phisap/assets/117558117/d8f0617c-b7db-4154-9e53-c28f13955473)
如图，因为装了两个python，用IDLE可以直接选版本

**Comment by kvarenzn** [comment]
那么有没有种可能，就是你的依赖装到了另一个版本的python中

对于你这种情况，可以使用
```powershell
py -3.11 -m pip install -r requirements.txt
```
来指定给3.11版本的python安装依赖

**Comment by zzy6011** [comment]
草，这下我小丑了，抱歉
