### ISSUE TITLE
arc闪退

### ISSUE THREAD

**Issue by doubilbm** [kvarenzn/phisap#12]
phigros能正常用但arc那个输入延时后回车就闪退了
![QQ图片20220207020731](https://user-images.githubusercontent.com/62131661/152694931-eb843445-b0cf-43a9-9238-eeff011b7f3b.png)
请问是怎么回事，或者是我哪里输错了吗

**Comment by kvarenzn** [comment]
不是。此问题稍后修复。

**Comment by kvarenzn** [comment]
您好，此问题应该已经修复，请`git pull`（或者重新下载本项目的源码压缩包）然后重试。

**Comment by doubilbm** [comment]
> 您好，此问题应该已经修复，请`git pull`（或者重新下载本项目的源码压缩包）然后重试。

确实，没问题了，辛苦了
说个题外话，感觉gui版比命令行的反应要慢不少，之前命令行在第一个note落到判定线一瞬间按空格是正好的，现在得提前半秒左右按，有点难把握，能不能优化一下（得寸进尺

**Comment by kvarenzn** [comment]
> 之前命令行在第一个note落到判定线一瞬间按空格是正好的

以前的命令行在Linux下有bug，经常按了按键后没反应，所以才改成gui的（Windows下没试过，不太清楚）

> 现在得提前半秒左右按，有点难把握

现在是用的tk库写的ui，可能是tcl解释器比较慢吧。下一版ui将用pyside（qt6）重写，应该会比现在快不少，到时候您再试试，如果还是慢的话就请再开个issue。
