### ISSUE TITLE
如图，使用模拟器和实体机都会出现触屏坐标偏移问题

### ISSUE THREAD

**Issue by 3121673169** [kvarenzn/phisap#126]
![a72679370e981fceac5e443ec9a620c](https://github.com/kvarenzn/phisap/assets/148664947/0439322c-6a47-468c-985e-4a69c34882a5)
如图，实际触摸坐标与铺面不相符，但确实是在运行的。

mumu模拟器：分辨率1920x1080  [HUAWEI] HUAWEI NCO-AL00 (Android 12)

**Comment by 3121673169** [comment]
使用的是dev，stable正常运行

**Comment by 364hao** [comment]
dev一个版本对坐标计算进行了调整，尝试下这个版本前的phisap

**Comment by 3121673169** [comment]
通过使用0.17版本已经解决问题，谢谢解答
