### ISSUE TITLE
无法正常使用 双端都闪退

### ISSUE THREAD

**Issue by TsukiCastilla** [kvarenzn/phisap#127]
**我的设备**
--PC--
系统：windows11 家庭版 22H2 x64
CPU：8代i5
内存：8G
--移动设备--
Device: vivo V2133A (Android 13)
型号以及系统？：Vivo X70 originOS 3
device_size = 2376x1080, codec_id = h264
CPU：天玑1200-vivo 8核 3.0GHz
内存：12G

**声明**
_确保你在提问前做到了下面两项，如果做到了任意一项，请在对应的中括号`[]`内敲入一个`x`，即`[x]`_
- [x ] 我搜索了Issues，没有人在之前提过类似的问题
- [x ] 三种规划算法我都有尝试过，全部无法AP

**谱面名称及难度**
本文内容Ark IN
此外我还试了Inverted world IN

**谱面信息**
官谱，则无需提供

**最佳成绩及对应的规划算法**
第一次尝试：用的stable版本

`安装最新的 PowerShell，了解新功能和改进！https://aka.ms/PSWindows

PS C:\Users\a1114> cd C:\Users\a1114\Desktop\phisap-stable
PS C:\Users\a1114\Desktop\phisap-stable> python main.py
1546366989000VJ
开始规划
正在统计帧... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:02
统计完毕，当前谱面共计44955帧
正在规划触控事件... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
规划完毕.
.\scrcpy-server-v2.0: 1 file pushed, 0 skipped. 29.7 MB/s (52867 bytes in 0.002s)
[server] INFO: Device: vivo V2133A (Android 13)
[client] device_size = 2376x1080, codec_id = h264
[client] 正在确认设备尺寸，请稍候
[client] 设备尺寸: 2376x1080
操作结束`

algo1：根本就用不了，一打开这个模式phisap没有报错就显示远程连接设备已终止
algo2：到这里的时候 ARK分数之到达1/10，但是出现严重卡顿以及闪退问题（描述：note不动了，音乐还在响，过一会会恢复流畅，但是过几秒手机就黑屏闪退了）手机闪退之后直接卡住了，接着我把数据线拔出，phisap和powershell也跟着闪退了

接着我去试了Dev版本：
ARK一样的情况，先是全perfect 然后手机卡顿在约1/10处，屏幕卡住不刷新，然后phisap未响应，接着phigros变得流畅，但是按键全空Miss

**出现Miss/Good/Bad的位置**
ARK：AP直至1/10处 后面就基本上都是 Miss 和 Good 了

**桌面端信息(请补充以下信息):**
见开头

**游戏设备信息(请补充以下信息):**
见开头

**附加信息**
安装的每一步我都反复检查过了，本人曾经有用过python，所以python解释器环境之类的是预先装好的，刚好是3.11版，并且我在出现问题的时候重装了python3.11 未果
值得一提的是：我在多次尝试ark失败后去尝试inverted world的时候，有一次竟在非常卡顿（屏幕全程过几秒一卡过几秒一卡的情况下）全连了

**Comment by ghost** [comment]
黑屏这个问题很多人都提过 大概率是编码的问题
我猜想是scrcpy一直会对设备视频流解码，导致手机性能严重下降
不过我的设备由于scrcpy不支持解码，所以从来没有过卡顿 如下
![Clip_2024-02-25_09-15-26](https://github.com/kvarenzn/phisap/assets/129530250/33fdaecc-7926-468f-b84d-bb979aafe0bf)

但是使用能够正确解码的解码器的也会出现卡顿 报错会消失
emm我还没啥解决办法，参考下 #52 ？
