### ISSUE TITLE
Arcaea无法配置

### ISSUE THREAD

**Issue by KaSock** [kvarenzn/phisap#129]
**声明**
_确保你在提问前做到了下面两项，每当完成了一项，请在对应的中括号`[]`内敲入一个`x`，即`[x]`_
- [x] 在提问前，我已经完整地阅读并理解了README.md的内容
- [ ] 我在Issues中搜索过，确保没有其他人提过类似的问题

**描述问题**
请清晰且简洁地描述你遇到的问题
延时设置完成后报错，疑似脚本问题

**如何复现**
复现此问题的步骤:
1. 输入坐标
2. 输入铺面文件
3. 输入延迟
4. 看到问题了

**预期行为**
请清晰且简洁地描述你期望的行为
正常启动脚本开始运行

**截图**
如果可行，请补充终端/程序界面截图
![image](https://github.com/kvarenzn/phisap/assets/56071624/030e9c23-4400-40b7-a05c-9b020d62bf72)

**桌面端信息(请补充以下信息):**
 - 操作系统及其版本: Windows 10 x64
 - 使用的phisap分支: dev
 - 使用的phisap版本: arcaea

**游戏设备信息(请补充以下信息):**
 - 设备型号: OnePlus
 - 系统版本: 雷电模拟器
 - 安卓版本: 7.1
 - adb版本: 1.0.41

**附加信息**
请在此补充任何其他的你认为必要的信息。

phisap正常运行 已执行命令pip install -r requirements.txt

**Comment by kvarenzn** [comment]
phisap今后将不再支持arcaea，请寻找其他替代品

**Comment by KaSock** [comment]
> phisap今后将不再支持arcaea，请寻找其他替代品

感谢作者回复，问题已经得到解决，我会将他的逻辑和功能完善，我作为这方面的初学者，用这个项目学习挺好的。
