### ISSUE TITLE
在模拟器上运行后可以正常开始，但不会发送触摸事件

### ISSUE THREAD

**Issue by D3caRab1an** [kvarenzn/phisap#13]
录屏如下，adb，python和phigros版本正确并且已经连接，adb可以发送指令，主程序正常打开并且可以解析apk

https://user-images.githubusercontent.com/91132226/152786558-af780fdf-e8f1-44d2-ae0c-8ee8dbdeb36b.mp4

录屏由于上传限制的原因比特率调的比较低，请见谅
非常喜欢您的这个项目，很久之前就有构想过自动打歌但苦于没有技术力，非常希望您能把这个项目继续做下去！

**Comment by kvarenzn** [comment]
您好，触摸事件已经正常地发送了，否则游戏不会自动重开。这种情况表明您需要手动调整延时时长（一般来讲延时时长那个选项不会是0，需要您多次摸索（对于不同设备这个值一般不同，在我的设备上时长在0.22左右，也没什么好的经验可以快速的得到这个值））。
如果您觉得这种方式比较麻烦，推荐您使用手动同步的方式，这种方式更易操作。

**Comment by D3caRab1an** [comment]
> 您好，触摸事件已经正常地发送了，否则游戏不会自动重开。这种情况表明您需要手动调整延时时长（一般来讲延时时长那个选项不会是0，需要您多次摸索（对于不同设备这个值一般不同，在我的设备上时长在0.22左右，也没什么好的经验可以快速的得到这个值））。 如果您觉得延时同步比较麻烦，推荐您使用手动同步的方式，这种方式更易操作。

已经解决了，谢谢您
