### ISSUE TITLE
建议在autoplay时向设备发送通知 预防yyw（

### ISSUE THREAD

**Issue by ZhengXieGang** [kvarenzn/phisap#17]
在自动打歌时向设备发送通知消息 有可能做到吗？

**Comment by kvarenzn** [comment]
做不到

**Comment by ZhengXieGang** [comment]
那就全靠玩家自觉喽？

**Comment by ZhengXieGang** [comment]
其实可以加一个adb备份的功能 解完歌 体验完后 想还原就还原

**Comment by kvarenzn** [comment]
> 那就全靠玩家自觉喽？

随便，这不归我管。稍后我会把我的想法在README里重申一遍

> 其实可以加一个adb备份的功能 解完歌 体验完后 想还原就还原

我没有这种需求，不会加的。想加请自己动手
