### ISSUE TITLE
无法游玩愚人节谱面

### ISSUE THREAD

**Issue by jialeyueyue** [kvarenzn/phisap#26]
algo1:
![PTV)IB)O`DVG724CN8_CUQ6(1).png](https://user-images.githubusercontent.com/81015649/161180695-8e281e54-5c10-4d24-bedf-f79d9cb20865.png)
可能是由于愚人节谱面的判定线在屏幕外导致无法规划点击
algo2:
可以规划方案,但是无法点击，输出结果如下图![)9V{(6}9U@UF~C00@)%9OT4.png](https://user-images.githubusercontent.com/81015649/161180916-fac4393f-07ee-48e6-ae80-65f99281ed06.png)

**Comment by kvarenzn** [comment]
最近没关注phigros的更新，不过你遇到的这个问题看着跟愚人节谱没太大关系。请问其他的谱面在你的设备上工作正常吗？

**Comment by jialeyueyue** [comment]
其他谱面倒是全部没问题
这次的愚人节谱面判定线在屏幕外面，所以打的时候（指手打）应该全部使用了垂直判定，似乎无法在屏幕外点击？

**Comment by kvarenzn** [comment]
在规划算法里已经考虑到了这种情况（三个月前更新的，当时是为了修复Nhelv无法金phi的问题），如果点击处在屏幕外则算法会自动根据判定范围求解在屏幕内的打击点。

可能是我算法写的有点问题，过段时间修复。

**Comment by jialeyueyue** [comment]
我尝试重新解包并使用algo2发现似乎可以进行点击了，但是可以点到向左上右三个方向下落的note，无法点击向下落的note

**Comment by jialeyueyue** [comment]
https://user-images.githubusercontent.com/81015649/161258784-5f078caf-8aa7-4c55-a35b-d735ba7b5fab.mp4

**Comment by kvarenzn** [comment]
这样看那确实是规划算法的问题，过几天我在自己的设备上试试。

说点题外话：
algo2这个算法比较激进，追求使用最少的指针（这里的指针你可以理解为手指头，安卓多点触控最多支持10个指针同时在屏幕上），它把hold拆成一个tap和一堆drag，flick拆成一堆drag，多个note共用一个指针。一般不常用，除非一些特殊的谱子（例如和喵塞克联动的那个，还有一个是最后八个长条落到一起的谱子叫啥我忘了）用algo1规划后发现某一时刻屏幕上有超过了10个指针的时候才用algo2。这个规划算法的缺点就是经常漏note（其实规划算法都规划到了，但它对计时器同步的精度要求比较高）。

我个人一般用的算法是algo1，与algo2相比比较保守，浪费指针，但能确保每个note都能点到。

另外，这个项目成型于去年1月左右（不过没有上传github），当时的版本就没法游玩光SP（当时只有algo1），没想到一年多了还是没法玩愚人节谱面，令人感慨（

**Comment by jialeyueyue** [comment]
主要是algo1好像会报错规划不出来(

**Comment by KHongSHu** [comment]
想要您一个联系方式（
