### ISSUE TITLE
Phisap的使用体验

### ISSUE THREAD

**Issue by XYboxl** [kvarenzn/phisap#27]
### 1.**门槛**
  **_使用此工具，门槛很高！高到什么程度？有些人用不来_**

我认为使用这个工具要具备一下条件：
_有电脑、有手机、有技术、有脑子、玩phigros_
可感，面对成山成海的垃圾推送广告，面对互联网千千万万的网页，来到这里并使用上的人是何等稀少!
令我疑惑的是，拿这个的人是将要拿它作甚？会有很多理由，我不多说。（因为我也是）

### **2.关于phisap**
使用完phisap后，对应的，游戏体验也会逐渐减少，动手打歌的意愿会越来越低，直到放弃phigros，因为它已经索然无味了
（个人感受，这个不对每个人都适用，对于游戏的热爱是不会因为一个工具而消失的（还是个人感受））
希望作者不要再开发更便捷的phisap了，越便捷，使用的门槛就越低，所谓的”大佬“会越来越多，关于phisap的言论也就越来越多，毕竟谁都不希望看到那样的景象，当然，也有我个人的私心在内（
### **3.体验**
当我看到phisap时，我愣住了，这......
Phisap只有看似简单的功能，但这个功能却不简单。何以见得？
1.解锁个人最想要的隐藏曲目
2.炫耀（小鬼行为欸）
3.爽一把
4.享受AP带来的快感（却不是自己打的）
还有很多......我知道，讲的十分浅显，没有那些专业的评论家评论的深刻，我尽力了。
说实话，我直到现在都没研究明白，等研究好了，一位RKS高达16.03的大佬就出现了（开玩笑

但，_这个工具已经很好了！_
### **4.个人疑问**

1.可以运用在课题模式吗？

2.在异象期间能发挥到同样的效果吗？

谢作者
（个人感受，不代表除了我自己以外的任何人。我知道，我在理解和语言方面会有错误，欢迎指出）
（注：”体验“这个部分中的“研究”一词是指正确使用phisap在phigros里达到AP一首曲目的效果）

**Comment by kvarenzn** [comment]
> 可以运用在课题模式吗

不能，达不到课题模式的精度要求

> 在异象期间能发挥到同样的效果吗

没看懂

**Comment by XYboxl** [comment]
> 不能，达不到课题模式的精度要求

感谢，期待关于课题方面的更新

> 没看懂

额，打个比方说，解RR时，走流程不是有时停？在走流程的时候可以用吗？

**Comment by kvarenzn** [comment]
> 感谢，期待关于课题方面的更新

不好说，这个属于同步计时器范围的问题，到现在为止都没有找到能称得上好的解决办法。所以极有可能以后也不会支持课题模式。当然如果你问的只是phisap能不能打课题模式，这个是能的，不过达不到all perfect，并且需要你手动操作切歌。目前使用phisap打课题模式最好的记录就是金48，彩48没打出来过。
给你一个使用phisap打课题模式的操作方案，仅供参考：
1. 选定你要打的三首歌，但先不要点开始
2. phisap的同步方式改成手动同步，规划算法改成algo1或algo2，先后选定你选择的这三首歌和对应的难度，在phisap上点击开始（注意此时phigros里仍不要点开始），开始按钮变成停止按钮后再点停止。这个操作对三首歌各执行一遍。这一步是让phisap提前规划手法并缓存规划结果以节省时间
3. 同步方式不动，规划算法改成不规划，重新选择第一首歌。在phigros上开始课题模式，手动控制phisap击打第一个音符。
4. 为了保留phisap的操作时间，可以在每首歌所有音符都打完但曲目还没播放完毕时双击左上角暂停，在暂停时操作phisap准备下一首曲目，再继续。

> 额，打个比方说，解RR时，走流程不是有时停？在走流程的时候可以用吗？

不知道你这里提到的‘时停“是指什么，不过RR确实能用phisap解。如果你指的是音符在下落过程中突然停止，那属于判定线表演，phisap读取的是原始谱面文件，可以识别这些情况。另外，README里那几张截图都是用phisap打出来的。

**Comment by XYboxl** [comment]
adb不链接手机时，main.py是可以正常打开吗?

**Comment by kvarenzn** [comment]
可以

**Comment by KHongSHu** [comment]
请问您是 如何配置好环境的呢？
我在配置环境的过程中出现了一点问题

**Comment by doubilbm** [comment]
> 当然如果你问的只是phisap能不能打课题模式，这个是能的，不过达不到all perfect，并且需要你手动操作切歌。目前使用phisap打课题模式最好的记录就是金48，彩48没打出来过。

可以彩48的，其实课题模式ap主要问题在能不能同步计时器，只要对准了就能百分百ap
附一张刚弄的
![QQ图片20220417225222](https://user-images.githubusercontent.com/62131661/163719910-8cc2cf92-5311-4023-a010-f137a14384f3.jpg)
