### ISSUE TITLE
窗口闪退

### ISSUE THREAD

**Issue by XYboxl** [kvarenzn/phisap#28]
帮忙看看哪里错了，一打开main.py就闪退，这是我遇到的最大的问题了

https://user-images.githubusercontent.com/103085668/162342383-f6cfbbb3-dcc6-4593-bf13-009c94f3e9d0.mp4

**当时是未链接手机的状态，python版本和adb版本都符合**

**请讲解的尽量详细，如果有文件没下，可以的话提供下下载链接，谢谢！**

**Comment by kvarenzn** [comment]
请你去补习一下git相关知识。主要看一下“分支（branch）”相关内容。

然后README里已经写得很清楚了，要使用本项目需切换到`main`分支

**Comment by XYboxl** [comment]
好的

**Comment by KHongSHu** [comment]
您好，想问一下您是如何运行成功的，我貌似和您遇到了一样的问题
