### ISSUE TITLE
feature request:full auto support and anti cheaters

### ISSUE THREAD

**Issue by qwedc001** [kvarenzn/phisap#4]
两个新功能的小请求.不一定下个版本就实装，但是请考虑一下。
1.游戏改为全自动模式，具体实现流程大致如下
(1)选定需要打的歌
(2)运行程序，程序对当前关卡页面使用adb截图+ocr识别，判定歌曲名以及难度（需要程序加强模糊搜索支持）（adb截图+ocr识别可参考明日方舟自动挂机项目[ArknightsHelper](https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper)的部分内容，里面使用了Windows10自预装的OCR。
(3)利用adb模拟点击按钮，进入游戏以后，如果需要重新对时间轴，也可以选择先暂停再重新开始
2.毕竟再怎么说这个工具也是有一定cheat嫌疑的，现在音游圈的混乱程度（尤其是phi圈的混乱程度）让我很担心这样一个高技术力的作品会被小鬼拿来装杯或者是被ky警察出警。所以有几个措施可以考虑一下。
(1).我注意到我的手机在运行程序时再次触控手机会无响应，只有结束程序运行以后才会恢复正常，这属于是bug还是feature？如果是bug，请务必修复，这样能有效的防止小鬼尝试以糊的手法录装杯手元（
(2)为什么要写第一条并且说明了要停留在关卡页面呢，因为这个页面是有用户名的，而利用OCR技术可以检测用户名，可以加一个设定，使用本程序时检测用户名必须为AutoPlay。这样也能避免装杯结算图的出现
当然了，这两个措施是防君子不防小人，但是还是希望音游圈能更好一点

**Comment by qwedc001** [comment]
另外，github可以对特定的issue上标签（labels），feature request一般上的标签是enchantment，bug report 一般也会上，便于区分

**Comment by kvarenzn** [comment]
> 1.游戏改为全自动模式，具体实现流程大致如下

这点其实我在写这个项目时考虑过。不过呢，有以下几个原因没有实装
+ 这属于个人写着玩的项目，个人觉得实装ocr的繁琐程度不亚于每次执行那些步骤（。
+ 诚然，如您所说，可以使用Windows 10的OCR，可是这个项目发布以前都是在Linux上开发/测试的。虽然也可以借助tesseract，不过那是个不小的库，这个项目的一个目标就是借助最少的依赖库。
+ 个人认为，这样的操作虽然繁琐，但可以有效地防小鬼。能愿意看并看懂我readme中写的步骤的，多半也能自己写一个类似功能的程序。

当然，既然都提issue了，那就表明这个功能还是有需要的，等那边发布2.0后我（可能）会加上，毕竟说是2.0 UI要大改，现在着急适配也没啥用。
> 2.毕竟再怎么说这个工具也是有一定cheat嫌疑的，现在音游圈的混乱程度（尤其是phi圈的混乱程度）让我很担心这样一个高技术力的作品会被小鬼拿来装杯或者是被ky警察出警。所以有几个措施可以考虑一下。
+ 不要怀疑，这就是个cheat工具（
+ 高技术力（笑）
+ 甭管玩啥，不混圈是常识
+ 这个项目我从来没有宣传过，唯一的获知途径就是上github上搜索phigros，还要倒序排列才能找到（笑）。一般人根本找不到这里，大可放心（
> (1).我注意到我的手机在运行程序时再次触控手机会无响应，只有结束程序运行以后才会恢复正常，这属于是bug还是feature？如果是bug，请务必修复，这样能有效的防止小鬼尝试以糊的手法录装杯手元（

看来不同安卓手机的实现差异确实是比较大的。在我的设备上，如果点击屏幕，手机会立即忽略这个程序发送的指令，只处理真实的屏幕触控输入，导致我每次cheat时都不敢碰屏幕（。过几天我再在模拟器上试试看表现如何。

> (2)为什么要写第一条并且说明了要停留在关卡页面呢，因为这个页面是有用户名的，而利用OCR技术可以检测用户名，可以加一个设定，使用本程序时检测用户名必须为AutoPlay。这样也能避免装杯结算图的出现

这个同上，也是等2.0发布之后再看看
> 另外，github可以对特定的issue上标签（labels），feature request一般上的标签是enchantment，bug report 一般也会上，便于区分

等以后issue多了再处理吧（），现在一只手就数得过来的issue实在没必要加label（。不过还是感谢您的建议

**Comment by qwedc001** [comment]
> 这个项目我从来没有宣传过，唯一的获知途径就是上github上搜索phigros，还要倒序排列才能找到（笑）。一般人根本找不到这里，大可放心（
您猜我是怎么找到这里的（答：闲的没事儿）

> 甭管玩啥，不混圈是常识
我不混圈，不一定表示圈内人不会过来冲我，现在很多人都很魔怔，小心行事最好。

> 个人认为，这样的操作虽然繁琐，但可以有效地防小鬼。能愿意看并看懂我readme中写的步骤的，多半也能自己写一个类似功能的程序。
您高估我的技术力了（笑

fine，那就先这样好了。这些功能以后再说。
