### ISSUE TITLE
一点力所能及的小建议

### ISSUE THREAD

**Issue by zzy6011** [kvarenzn/phisap#41]
关于如何实现iOS设备的无越狱远程控制我在网上查了下，主播可以研究下[WebDriverAgent](https://github.com/facebook/WebDriverAgent)
还有XCUITest
具体可以看下csdn这篇文章https://blog.csdn.net/yxys01/article/details/76922247?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7EPayColumn-1-76922247-blog-81201235.pc_relevant_3mothn_strategy_and_data_recovery&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7EPayColumn-1-76922247-blog-81201235.pc_relevant_3mothn_strategy_and_data_recovery&utm_relevant_index=1

**Comment by kvarenzn** [comment]
感谢，之后会去研究一下的
