### ISSUE TITLE
小白一个，想问下准备里的2.pip install -r requirements.txt意思

### ISSUE THREAD

**Issue by lianqiannian** [kvarenzn/phisap#42]
可能有点过于幼稚了，望答复

**Comment by QuarterTime** [comment]
> 可能有点过于幼稚了，望答复

安装文本里写好的包，省着你一个一个pip install <包名>

**Comment by kvarenzn** [comment]
好家伙，钓鱼是吧，你都有穿过阻碍进入github的能力了，为啥不对这个问题直接进行一个索的搜呢
