### ISSUE TITLE
scrcpy报错

### ISSUE THREAD

**Issue by zzy6011** [kvarenzn/phisap#45]
如图
![image](https://user-images.githubusercontent.com/117558117/215320745-3a6ef9f7-86db-42a8-a03c-bbbf9c447d07.png)
在网上查到了解决方法但是不知道如何操作
![image](https://user-images.githubusercontent.com/117558117/215320752-4dd44d91-1684-4c33-afe6-c96674f936a9.png)
求助qwq

**Comment by kvarenzn** [comment]
有两件事需要确认一下：
1. 我看你的第二张截图上的scrcpy版本是1.23，事实上1.23确实存在编码器的问题，不过据说scrcpy的作者已经在后续的版本1.24中给修复了，所以，你遇到的问题是否在最新版的scrcpy(v 1.25)上依然存在？（这里指的是scrcpy，不是phisap，下同）
2. 接着(1)的问题，如果确实依然存在，是否传递一个解码器选项`--encoder xxx`就可以解决此问题？

如果1、2的问题答案都是“是”的话，那么之后我会给phisap加一个选项用于选择编码器，以解决此问题

**Comment by zzy6011** [comment]
第一个问题：哦第二张截图是您看错了吧，那是那个网页上的截图，不是我自己的。
第二个问题：我就一无能yyw，什么传递一个解码器选项我也看不懂，我是想尝试自己把图2的解决方法的代码写进去的，但是啥也不会。那个scrcpy.exe的东西我可以用图二的代码运行显示手机画面，并且发现每次运行main.py的开始按钮后图一的规划触控事件规划完毕后会在手机屏幕的x200y200处点击一下。

**Comment by kvarenzn** [comment]
> 那个scrcpy.exe的东西我可以用图二的代码运行显示手机画面

我猜你应该懂一些基础的命令行知识吧（比如什么是命令行，什么是命令行参数之类的）
那么你这里在运行scrcpy.exe的时候是直接运行(双击scrcpy.exe或是在命令行中输入`scrcpy.exe`运行)的还是加了一个额外的`--encoder OMX.google.h264.encoder`参数之后再运行的？

**Comment by zzy6011** [comment]
cmd运行的scrcpy --encoder 'OMX.google.h264.encoder' -m 1024

**Comment by kvarenzn** [comment]
有没有尝试过不带任何参数直接运行scrcpy？还是说如果不带任何参数直接运行scrcpy会报错？

**Comment by zzy6011** [comment]
我去，我刚试了下，这次可以显示手机画面了，以前都不行的
`C:\Users\Administrator\Desktop\scrcpy-win64-v1.25>scrcpy
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
C:\Users\Administrator\Desktop\scrcpy-win64-v1.25\scrcpy-s... file pushed, 0 skipped. 75.6 MB/s (42151 bytes in 0.001s)
[server] INFO: Device: vivo V2054A (Android 11)
[server] ERROR: Encoding error: java.lang.IllegalArgumentException: null
[server] INFO: Retrying with -m1920...
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2408
INFO: New texture: 864x1920`
![image](https://user-images.githubusercontent.com/117558117/215467732-d4467e6d-3547-4c17-bed1-5a2062e71fdc.png)

**Comment by kvarenzn** [comment]
那我知道了，下次更新加一个选项

**Comment by zzy6011** [comment]
okok ：）
