### ISSUE TITLE
2.4.2版本可以正常运行但是2.5不行？

### ISSUE THREAD

**Issue by jsjsjsjsjsjsjson** [kvarenzn/phisap#48]
我解包了2.5版本的phi后尝试开始但python会输出一串字'numOfNotes'然后就没有下文了，但2.4的包解包后仍可正常运行，我猜想是鸽游改变了谱面文件的格式，请您帮忙看看，我真的很喜欢草先生的新曲子（

**Comment by kvarenzn** [comment]
可能已经修复了，请更新一下phisap再重试一次

**Comment by jsjsjsjsjsjsjson** [comment]
谢谢
/close
