### ISSUE TITLE
“手动同步”似乎失效

### ISSUE THREAD

**Issue by luohebing** [kvarenzn/phisap#56]
![image](https://user-images.githubusercontent.com/41121178/233785460-312d17dc-4691-41b5-af64-b3d5c8fa74e3.png)
当前使用“手动同步”时，无法在帧统计完成后再次点击“开始”以开始打歌。再次点击“开始”将重新开始统计帧。

**Comment by kvarenzn** [comment]
刚开了一局Burn IN，没有出现你说的这种情况，不过根据经验，我猜可能还是adb的配置问题，跟是否是手动同步应该关系不大

根据你的截图，没有出现那行`./scrcpy-server-v1.25: 1 file pushed, 0 skipped`，那么应该是卡在执行`adb push`这条命令上了

**Comment by luohebing** [comment]
是我犯傻了，拉取更新后没有载入scrcpy
抱歉占用时间Orz

**Comment by kvarenzn** [comment]
啊这，小事，无需在意
不过本次更新并没有包含对解码器问题的修复代码，可能你还得需要修改一下`control.py`中的命令行参数
