### ISSUE TITLE
Error in "Luminescence IN"

### ISSUE THREAD

**Issue by luohebing** [kvarenzn/phisap#57]
![image](https://user-images.githubusercontent.com/41121178/233790194-3e9ed9f5-9550-4378-80bf-bbf274e7a0a9.png)
似乎愚人节铺面出现过类似问题，可能是某些特殊演出Note？
该曲是主线第八章解锁魔王曲的前置，可以的话希望看下(。・ω・。)

**Comment by kvarenzn** [comment]
好，我第八章还没解锁，解锁了之后我再看看
单从报错上来看，应该是同一时刻要按的地方超过了10个，跟特殊演出note没有关系
不过刚才试了一下，貌似algo2规划算法没报错，应该能用?
算法1跟2的区别就在于2比较“省指头”，可以在规划时合并一些note的判定区

**Comment by luohebing** [comment]
原来如此，问题已解决，感谢作者
