### ISSUE TITLE
使用时scrcpy报错

### ISSUE THREAD

**Issue by MythicAqua** [kvarenzn/phisap#59]
开始后出现此报错，没有触摸事件;-;

![phisap](https://user-images.githubusercontent.com/122416024/233847989-b1e42134-aae7-4b1e-afeb-744e9f13cf0c.jpg)

adb版本 1.0.41
设备 红米 Note 10
MIUI 12.5.9
Android 11
如果单独使用scrcpy-win64-v2.0中的scrcpy.exe可以正常唤出窗口进行点击操作

**Comment by kvarenzn** [comment]
两个解决方案，二选一：
1. 使用scrcpy-server-v1.25
2. 更新phisap到最新版：重新下载源码包或者`git pull`

**Comment by MythicAqua** [comment]
解决了，非常感谢:D
