### ISSUE TITLE
exteact error

### ISSUE THREAD

**Issue by Matrix-CN** [kvarenzn/phisap#6]
D:\phisap-main>python extract.py "D:\phisap-main\base.apk"
Traceback (most recent call last):
  File "extract.py", line 14, in <module>
    from utils import read_string_end_with_nil
  File "D:\phisap-main\utils.py", line 5, in <module>
    def distance_of(p1: tuple[float, float], p2: tuple[float, float]):
TypeError: 'type' object is not subscriptable

**Comment by kvarenzn** [comment]
请使用3.8.0及以上版本的Python。稍后我会将这条添加到README中。

**Comment by Matrix-CN** [comment]
应该使用Python 3.9.0及以上 我使用Python3.9问题解决

**Comment by kvarenzn** [comment]
感谢指正
