### ISSUE TITLE
adb: error: failed to get feature set: device offline

### ISSUE THREAD

**Issue by Kenri004** [kvarenzn/phisap#61]
使用模拟器：蓝叠模拟器
已更新至最新版本，确认依赖安装完毕，使用scrcpy-server-v2.0
显示adb无法连接设备，但是应该是配置好了
点击开始会报错，具体信息如图，然后phisap会进入未响应状态，只能强行关闭
![QQ截图20230427223437](https://user-images.githubusercontent.com/110974392/234896676-f2e356f0-5111-4056-802b-9a9520a2c867.jpg)

**Comment by kvarenzn** [comment]
其实还是adb的问题
phisap目前不支持多设备同时连接，请等待后续版本更新
不过我比较好奇的是为什么开了蓝叠模拟器后会有两个adb设备，正常来讲应该一个模拟器对应一个设备

**Comment by kvarenzn** [comment]
百度了一下，`emulator-5554`应该不是一个安卓设备，貌似是有其他应用程序占用了`5555`端口导致adb误认为这是个设备
所以，一个临时的解决方案是：
如果你能找出哪个程序占用了5555端口，把它终止了应该phisap就能正常工作了

**Comment by Kenri004** [comment]
换成了夜神模拟器，然后出现了更奇怪的错误（）
![QQ截图20230428120105](https://user-images.githubusercontent.com/110974392/235051338-893423a5-2cb7-4014-b8fb-652c080c2b46.jpg)
如图所示为两个cmd窗口，左边先打开，确认adb已连接到模拟器并可以执行相关调试操作（如安装软件，查包名）
然后右边在phisap-main文件夹内打开cmd并运行main.py
我使用的是不规划（缓存算法），算法规划没有问题
然后就出现了如右边窗口所示的错误，同时程序崩溃
此时再回到左窗口运行adb devices
发现设备没了
自己捣鼓了几十分钟毫无头绪，求解()

**Comment by kvarenzn** [comment]
看来可能是linux上的adb行为跟windows上的有些差异导致的。可能`adb kill-server`在windows上会导致一些问题。
我今早上刚推了几个更新，可能会解决你的问题。

如果你是用`git clone`直接克隆的phisap，那么你执行这两行
```powershell
git pull  # 拉取最新的更新
git checkout a5d6653  # 检出最新版的前一个版本
```

如果你是在github上下载的源码包，那么你下载[这个包](https://github.com/kvarenzn/phisap/archive/a5d6653e09de863a7cde0604c064b169986951fb.zip)，解压覆盖掉你的phisap-main文件夹

然后再试一次，看看是否还有问题

**Comment by kvarenzn** [comment]
对了，重试之前记得要重启你的模拟器，然后再使用`adb kill-server`和`adb start-server`重启`adb`

**Comment by kvarenzn** [comment]
如果还有问题，那么你再重启模拟器和adb，然后依次执行下面的命令

```powershell
cd phisap-main  # 定位到你的phisap副本根目录下
adb push scrcpy-server-v2.0 /data/local/tmp/scrcpy-server.jar  # 推送服务端到安卓设备
adb reverse localabstract:scrcpy_114514 tcp:27188  # 在端口27188建立反向通信隧道
adb reverse --remove localabstract:scrcpy_114514  # 移除上一步建立的反向通信隧道
```
看看有没有报错，如果有的话，发一下报错文本或截图

**Comment by Kenri004** [comment]
我下载了最新版本的安装包，成功解决了上述问题，感谢你的帮助
然后新的问题出现了（）
触控事件似乎发送失败了
![QQ截图20230428130018](https://user-images.githubusercontent.com/110974392/235059591-c3be7b42-2fea-456b-ba01-83b955e94d96.jpg)
规划完毕后就毫无反应了
同时我自己试了一下scrcpy-v2.0
可以进行点击，但似乎提示好像是模拟器安卓版本过低？
![2](https://user-images.githubusercontent.com/110974392/235059859-8f70fc89-0af9-401f-ae1a-b03a5a067884.jpg)

**Comment by Kenri004** [comment]
我下载了最新的安装包，解决了上述问题，感谢你的帮助，现在adb可以成功连接了
但是新的问题是触控发送失败了（）
![QQ截图20230428130018](https://user-images.githubusercontent.com/110974392/235060132-49460638-b364-4dac-b197-90c0d7f4c0c2.jpg)
同时我试了一下使用scrcpy-v2.0，发现可以运行和点击
不过似乎有提示模拟器安卓版本过低
![2](https://user-images.githubusercontent.com/110974392/235060236-7042ce79-7482-42b5-8127-f0cdb86de7ec.jpg)

**Comment by kvarenzn** [comment]
延时同步功能目前是废的，但由于没什么人用所以也懒得修()，请使用手动同步
当然如果你发现手动同步也用不了，那就再告诉我一声
