### ISSUE TITLE
在phigros 3.0.0.1版本中 加载文件进度卡住

### ISSUE THREAD

**Issue by BiliSYS** [kvarenzn/phisap#62]
在phigros 3.0.0.1版本中 加载文件进度卡住
python版本：3.10.9

![image](https://user-images.githubusercontent.com/97880172/235106969-c131e302-5527-42f3-b111-f4bca3dff4b6.png)

卡在9%后无法加载

**Comment by kvarenzn** [comment]
已修复

**Comment by BiliSYS** [comment]
感谢
