### ISSUE TITLE
开始操作后触控无反应

### ISSUE THREAD

**Issue by BiliSYS** [kvarenzn/phisap#63]
触控规划结束后无操作
设备信息: MIUI 12.5.6 ; Redmi K20 Pro Premiui Edition
![image](https://user-images.githubusercontent.com/97880172/235190629-de46fa31-4b1f-4eeb-9bf6-1efadd4e04ed.png)
开发者设置内 "USB调试（安全设置）"已打开
安卓版本: 11
adb环境已配置
scrcpy-server-v2.0已放置到phisap主目录

**Comment by kvarenzn** [comment]
是否尝试过“手动同步”？能否正常工作？

**Comment by BiliSYS** [comment]
感谢指导 已可用
