### ISSUE TITLE
在使用华为matepad 10.4时，忽略触摸事件

### ISSUE THREAD

**Issue by huangacid** [kvarenzn/phisap#64]
环境：python 3.10.11 ；adb版本1.0.41； scrcpy 版本：2.0.0；设备：HUAWEI BAH4-W39 (Android 10)报错信息如下：
![屏幕截图 2023-05-07 053006](https://user-images.githubusercontent.com/132374589/236647533-69a6e7d3-e4dc-42c9-857c-99dde9bc2b63.png)
网上说的都试过了

**Comment by kvarenzn** [comment]
将在下一次更新中修复

一个临时的解决方案是，在`control.py`的第48行之后插入一行
```python
            'max_size=1920',
```
修改完后应该类似于
```
#...
            'log_level=info',
            'audio=false',
            'max_size=1920',
            'clipboard_autosync=false',
#...
```
保存后重试

**Comment by kvarenzn** [comment]
另外，我没有过安卓平板，也没见有人开过类似的issue，不过据说平板上的Phigros的长宽比是4:3，而phisap默认长宽比是16:9，所以可能会遇到一些note漏判的情况。如果你遇到了类似的情况，请再开个issue，我将在之后为平板加上适配

**Comment by huangacid** [comment]
还是老问题环境python 3.11.3
![屏幕截图 2023-06-12 163718](https://github.com/kvarenzn/phisap/assets/132374589/d5f8c0c1-94d7-4356-8e6c-c39e16f1f915)
更新后就这样了

**Comment by kvarenzn** [comment]
啊这，我没等到你的反馈，所以没有针对你的问题进行更新修复
我手上没有matepad设备，模拟器也没法模拟出你遇到的问题，所以得需要你来确认一下
你先按照我上边提供的临时解决方案尝试一下，看看是否仍有同样的问题，无论是否有都请你给一个反馈，之后我在按照你的反馈进行更新修复，谢谢配合

**Comment by huangacid** [comment]
还有

**Comment by huangacid** [comment]
怎么说呢，我发出来的时候就先按临时解决方案，它就出现了这个问题

**Comment by huangacid** [comment]
然后我重启了一下没再动文件它又好了

**Comment by kvarenzn** [comment]
那么请问你是否是在打开phigros前运行的phisap？

**Comment by huangacid** [comment]
不是

**Comment by huangacid** [comment]
启动后再运行的

**Comment by huangacid** [comment]
是的

**Comment by huangacid** [comment]
又出现了

**Comment by huangacid** [comment]
我现在是横屏的状态。但是它给我识别出来的

**Comment by kvarenzn** [comment]
...草

你是否有尝试过直接使用scrcpy？能否正常工作（即能够用电脑控制你的matepad）？

**Comment by huangacid** [comment]
是可以的

**Comment by kvarenzn** [comment]
> 是可以的

好，那我再研究研究


> 我现在是横屏的状态。但是它给我识别出来的

请问你这里是否想发一张图片？我没看到

**Comment by huangacid** [comment]
![image](https://github.com/kvarenzn/phisap/assets/132374589/12552e87-4655-4923-9977-1628236b9ad3)
![377744E1AE136C5A5E88705A7A078929](https://github.com/kvarenzn/phisap/assets/132374589/d6be5d8a-02b5-4b83-ac48-f8377c1ade14)

**Comment by kvarenzn** [comment]
thx

**Comment by kvarenzn** [comment]
刚推了个更新，你看看能不能解决你遇到的问题？

这次更新引入了一个新的依赖库，需要你重新执行`pip install -r requirements.txt`

**Comment by huangacid** [comment]
现在可以了
![屏幕截图 2023-06-14 142318](https://github.com/kvarenzn/phisap/assets/132374589/2fe672af-9a1e-417f-8411-8f6c34bdab6b)
但出现了这个

**Comment by kvarenzn** [comment]
中间的这段报错属于正常现象，可以忽略
