### ISSUE TITLE
能加个显示手机屏幕的功能吗（

### ISSUE THREAD

**Issue by zzy6011** [kvarenzn/phisap#69]
如题

**Comment by kvarenzn** [comment]
没懂，你是想要一个在电脑端看手机屏幕内容的功能吗？（重新实现一遍scrcpy client？）
以前尝试搞过，不过没找到比较高效的h264视频流解析库，`av`这个库太慢了，不仅会导致视频很卡，而且还会拖慢触控事件发送的频率，导致爆good或bad

**Comment by kvarenzn** [comment]
不过由于现在phisap支持scrcpy多开，你可以在运行phisap的同时再开一个scrcpy，应该可以达到你要的效果
