### ISSUE TITLE
建议修改License

### ISSUE THREAD

**Issue by qwedc001** [kvarenzn/phisap#7]
未成年限制注意到了
同时也注意到您的License使用的是WTFPL License，这个License允许别人随意修改程序，哪怕在注释里严禁了此项
注释只能起到道德约束作用，并没有实际效力（虽然换个License也会有人私下里偷偷用但这也是不可控的）
但换License可以避免一些不必要的麻烦产生，可以考虑MIT或者GPL的License

**Comment by qwedc001** [comment]
更正：MIT License允许用户随意修改，建议使用GPL License

**Comment by kvarenzn** [comment]
可能您误会了我的意思了，我本意**并没有禁止**他人修改我的代码，只是**不想承担**其他人因为修改我的代码所造成的**后果**罢了。
另外，未成年限制这东西就图一乐，不要当真。
