### ISSUE TITLE
解包错误

### ISSUE THREAD

**Issue by Vexterr** [kvarenzn/phisap#73]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/Vexter/Desktop/phisap/main.py", line 99, in <lambda>
    self.extract_btn = ttk.Button(frm, text='解包Apk', command=lambda: extract_apk(self.console))
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Vexter/Desktop/phisap/main.py", line 34, in extract_apk
    catalog = Catalog(apk_file.open('assets/aa/catalog.json'))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/zipfile.py", line 1547, in open
    zinfo = self.getinfo(name)
            ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/zipfile.py", line 1476, in getinfo
    raise KeyError(
KeyError: "There is no item named 'assets/aa/catalog.json' in the archive"
<img width="753" alt="Screen Shot 2023-06-22 at 4 45 30 PM" src="https://github.com/kvarenzn/phisap/assets/131033196/9d388833-048b-405c-a755-ea6934a129d9">
<img width="258" alt="Screen Shot 2023-06-22 at 4 46 36 PM" src="https://github.com/kvarenzn/phisap/assets/131033196/785b529f-a91f-499d-8641-03eacb4a6718">

看了另一个解包有问题的，已经下载1.3GB的apk了但还是有这个错误
从Google Play Store下的apk

Python 3.11
macOS Catalina (10.15.6)
Galaxy S23 Ultra, Android 13
APK版本3.1.0

**Comment by kvarenzn** [comment]
没有尝试过google play版的，我之前都是安装的taptap版，然后从手机的/data/提取安装包
我这边提取出来的安装包的md5 hash应该是`01e7e21604a07a3690cd42bb6ebe4b99`，且精确大小应该是`1462488223`字节

你可以用命令`md5 ./Phigros.apk`看看你的安装包的md5 hash是多少

不过你这安装包`assets/`目录下就一个`bin/`，那确实提不出东西来

**Comment by kvarenzn** [comment]
刚下了一个Play版看了一眼，目录结构确实跟taptap版的不一样
那么下次更新将会加上对play版解包的支持
如果你等不及下次更新，那么你可以在网上找一个taptap版的全量包先用着，这两个版本的谱面应该没有太大变化

**Comment by Vexterr** [comment]
谢谢大佬

**Comment by kvarenzn** [comment]
Google Play版需要提取并解包obb文件，具体操作步骤已经写进README了
