### ISSUE TITLE
单曲精选集中的《Break Over》AT难度无法AP

### ISSUE THREAD

**Issue by Vexterr** [kvarenzn/phisap#74]
歌打一半的时候判定线飞上去一堆蓝键会miss, 两个algo都试过了

**Comment by kvarenzn** [comment]
刚打了一遍，没有问题
![Screenshot_20230626-210458](https://github.com/kvarenzn/phisap/assets/12197126/de902dd0-02ae-4867-956e-d16ef7e25597)
3.1.0里的所有曲子都能AP，README里已经说了

**Comment by Vexterr** [comment]
https://github.com/kvarenzn/phisap/assets/131033196/8b8f7384-e67a-4dec-8969-5e871a8602b3

视频看着有点卡但是我录的时候差不多60fps，已经手动计时好几次了，只有这个地方打不了

**Comment by Vexterr** [comment]
稍微测试了一下，我屏幕边框有那么一点点不到，可能判定线飞上去的时候正好飞到了

**Comment by kvarenzn** [comment]
跟设备没关系，我的一加7P分辨率是2340x1080也能AP

你这明显是计时器同步没做好，音符击打的时间过早
如果同步成功，那么音符在被击打时应该能正好跟判定线重合（也就是音符跟判定线重合后消失），你这音符还没落到判定线就消失了
如果一开始时计时器同步没做好，你也可以使用“微调”功能补救一下，不过不推荐往那个输入框里直接输入数字，可以用鼠标滚轮或输入框旁边的上下按钮对微调值每次增减0.01s，这个改动是实时生效的，所以你可以一边调一边观察音符被击打时的位置

像你视频里这种情况，应该得延后个0.03s左右

**Comment by kvarenzn** [comment]
当然也不用调得100%重合，像视频里这种的就行
完整视频传不上，剪了个片段

https://github.com/kvarenzn/phisap/assets/12197126/d1c68834-381e-40b5-96c7-2fd335a8b738

**Comment by Vexterr** [comment]
又试了一次，两个algo而且是100%重合，还是不行。判定线飞上去后就miss，我windows笔记本正在维修，等修好了再试试模拟器

**Comment by Vexterr** [comment]
感觉挺奇怪的，就这个不能AP，Spasmodic跟Igallta都AP了

**Comment by Vexterr** [comment]
Nhelv一次就ap了，打算试试AVD

**Comment by Vexterr** [comment]
![Screenshot_20230627_170009_Phigros](https://github.com/kvarenzn/phisap/assets/131033196/09ef6a30-7139-41f6-b8c1-f2ef7f8f49ba)
过了

**Comment by Vexterr** [comment]
删了个文件就修好了，不知道为啥

**Comment by Vexterr** [comment]
Rrhar'il一堆粉键又打不了了，还是两个algo都试了而且计时也没做错，是不是跟电脑有关？

**Comment by kvarenzn** [comment]
电脑的问题估计不太可能，毕竟程序运行的结果都是一致的。我觉得有可能还是跟游戏设备有关，不过我并没有三星设备，所以这只是我的猜测。

**Comment by kvarenzn** [comment]
不过flick丢判这算是个老生常谈的问题了，我刚才更新了一下phisap，把原先的flick滑动方向从垂直于判定线改为了平行于判定线，不太确定能否可以解决你的问题，你可以试试

**Comment by Vexterr** [comment]
比之前好点，但划完会卡一下然后miss，这部分会显示个error
<img width="579" alt="Screen Shot 2023-06-29 at 6 38 23 PM" src="https://github.com/kvarenzn/phisap/assets/131033196/90b985ba-c2a4-47f3-bfba-1ae324bd6c77">

**Comment by kvarenzn** [comment]
这个error是视频解码器报的，可以忽略

**Comment by Vexterr** [comment]
![Screenshot_20230629_230722_Phigros](https://github.com/kvarenzn/phisap/assets/131033196/ef4175c1-2a09-4f27-8348-210197be3f95)
好耶

**Comment by Vexterr** [comment]
这种超难的歌只有5-10分钟的时间打，手机热了就打不了了

**Comment by kvarenzn** [comment]
> 这种超难的歌只有5-10分钟的时间打，手机热了就打不了了

啊？原来会这样吗，看来是手机在后台持续进行视频编码导致的，不过可惜的是scrcpy的视频编码关不掉，除非改server端的源代码
话说三星是不是会过热降频啊，然后就会降低处理触控事件的频率，继而导致miss

**Comment by Vexterr** [comment]
过热确实会降一些，就容易miss
