### ISSUE TITLE
服务端不需要解压吗？

### ISSUE THREAD

**Issue by ccy12023** [kvarenzn/phisap#75]
作者你好，请问下载下来的文件（scrcpy-win64-v2.1.zip）需要解压吗？是不是直接放在软件根目录？
[scrcpy-win64-v2.1.zip](https://github.com/kvarenzn/phisap/files/11928373/scrcpy-win64-v2.1.zip)
希望能尽快回答，谢谢作者。

**Comment by ccy12023** [comment]
你可以详细给我说一下操作步骤吗？我从来都没有用过这个软件，也不知道如何操作。

**Comment by kvarenzn** [comment]
你好

首先，我README里已经写得很清楚了，就在“如何使用”的“准备”一节，特别是序号为4的那项，你一定没有看完

其次，phisap并不是一个无门槛软件，如果你看不懂README里的描述，那说明这款软件不适合你，不推荐你使用

最后，根据我在README“遇到问题？”一节中说过的，我将关闭你开的issue

**Comment by ccy12023** [comment]
对不起我把文件下错了
