### ISSUE TITLE
请问是否加入了对4:3型设备的适配

### ISSUE THREAD

**Issue by Kenri004** [kvarenzn/phisap#78]
如题，我是在模拟器中运行的，在调整模拟器分辨率时发现4:3时会存在大量断触（很多平板应该也是这个分辨率？）
具体分辨率为2160*1620
在16:9的分辨率下能正常工作
所以想问一下有没有做其他分辨率的适配，如果没有会不会在后续版本中更新呢

**Comment by Kenri004** [comment]
![QQ截图20230708120636](https://github.com/kvarenzn/phisap/assets/110974392/7ac8eaaf-8fce-41b3-b24b-85d2ca8f0bae)
补一张图，谱面为狂喜AT

**Comment by kvarenzn** [comment]
你好，目前并没有适配4:3的屏幕。因为我没有安卓的平板，平时拿来测试的AVD模拟器也只模拟了Google Pixel 2
不过有计划在今后的更新中加上对其他格式的支持
顺便想问一下，同一个谱面，是不是在平板上播放的时候就看起来像被纵向拉伸一样？

**Comment by Kenri004** [comment]
好的，感谢回答
>顺便想问一下，同一个谱面，是不是在平板上播放的时候就看起来像被纵向拉伸一样？

确实是这样的

顺带一提我自己乱搞时的发现
不管16:9还是4:3设备上运行phigros都会占满整个屏幕
相对来说4:3设备的谱面看起来就被拉伸了一样
而我的小米手机是3200*1440的分辨率，运行phigros时无法占满屏幕，会在两侧留有黑边
但phisap可以在我的手机上正常运行（）

**Comment by Kenri004** [comment]
忽略我的反复reopen和close，网卡了（）

**Comment by kvarenzn** [comment]
> 而我的小米手机是3200*1440的分辨率，运行phigros时无法占满屏幕，会在两侧留有黑边
但phisap可以在我的手机上正常运行（）

phisap会自动根据屏幕长宽比计算黑边的尺寸，然后根据计算结果调整触控的位置。不过目前只支持根据宽高比16:9来计算黑边，所以在平板上无法正常工作

**Comment by kvarenzn** [comment]
你好，最新版(v0.6)尝试加入了对4:3屏幕的支持，需要手动选择宽高比为4:3。你可以看看效果如何

**Comment by Kenri004** [comment]
好快的更新
试了一下，已经可以在4:3设备中正常运行，orzorz
虽然好像偶尔会good/miss，但应该是我延迟没调好
顺带一提打开后就开始一直在cmd窗口弹这个报错，但是似乎对功能没有影响
![1](https://github.com/kvarenzn/phisap/assets/110974392/a5fc7615-bd98-471c-b44d-56052904dad5)

**Comment by kvarenzn** [comment]
这个报错是视频解码器报的错，不过由于phisap没有用到除宽和高之外的其他视频数据，所以这些错误可以忽略
