### ISSUE TITLE
是我自己server没有编译好吗？

### ISSUE THREAD

**Issue by BMC-Gordon0921** [kvarenzn/phisap#8]
本人设备华为BTV-DL09（老设备中老设备了，xb）
已经按照author大大写的步骤做到了编译server的地方
配置完成后跑main.py
都是弹出[server] INFO: 灞忓箷灏哄: 1920x1080后程序就没了动静。
尝试过各个分支，但直觉感觉应该是哪个地方配置出现问题？（手动滑稽）
VS Code调试也没有对任何程序报错……
为了最后一步尝试了一整个国庆假期……学生党表示晕倒（orz）
）本人只是为了把db doll 的1good消灭（笑）

实在不行就等鸽游出2.0后author大大的2.0大更新了。

**Comment by BMC-Gordon0921** [comment]
（author大大在几小时内就处理了问题……速度惊人

FINE，我这个周末再去试试看no-streaming的分支。

此外，我自己尝试的时候也看到 Issue #3 #5里也有提到author大大是在Linux下完成的程序调试工作。而我这种一般人只能用的起Windows（笑）所以bash窗口的命令和make命令就直接告别了我们的cmd和bat……（这应该也是一个等待解决的系统兼容？）

还有，预编译的Server是直接丢进./server还是下载源码解压后再移进去？如果直接下载那么这个server需要添加后缀名吗？
电脑有的时候会在输入打歌信息之后弹出
cannont stat './server/phisap-server: No such file or directory'
（我应该没拼错）

**Comment by kvarenzn** [comment]
那确实是版本问题，1.0.31应该是2014年之前发布的，有点老旧了。替换成1.0.41版本或许可以解决。

**Comment by BMC-Gordon0921** [comment]
啊，那么建议author大大修改一下README，避免其他人（虽然可能没有人）像我一样踩坑（真挚微笑）

**Comment by BMC-Gordon0921** [comment]
问题已基本得到解决，author大大也已将该问题和注意事项写入README。

本issue暂时关闭。
