### ISSUE TITLE
解析一些自制谱面时报错铺面

### ISSUE THREAD

**Issue by how2che4t** [kvarenzn/phisap#80]
![image](https://github.com/kvarenzn/phisap/assets/113228077/332044b4-80f2-4055-bcd2-2d4434792cea)

**Comment by kvarenzn** [comment]
谱面文件传一下

**Comment by how2che4t** [comment]
[27337550.zip](https://github.com/kvarenzn/phisap/files/11994997/27337550.zip)

**Comment by kvarenzn** [comment]
已修复

**Comment by how2che4t** [comment]
效率好高😦
