### ISSUE TITLE
关于Rrhar'ilAT中红键的问题

### ISSUE THREAD

**Issue by 364hao** [kvarenzn/phisap#82]
作者大大好，手机为OPPO_K10,系统是ColorOS13。操作系统为Windows11，在Rrhar'ilAT中红键海时会出现断连，且过后会断触一段时间。Phigros为3.1.1版本
以下为演示视频，已经关闭各种系统手势，把触控灵敏度拉到了最大。Phisap为最新版。
虽然时间对的不是很准但应该不会影响红键吧.jpg。算法是激进算法。已经困扰我好几个星期了www。

https://github.com/kvarenzn/phisap/assets/129530250/9988efa6-dd98-4a35-a5f3-f7ecc2f39704

![Screenshot_2023-07-15-10-44-37-07_a1b0c65cc4fc256422e0788e5ad09ca0](https://github.com/kvarenzn/phisap/assets/129530250/6976ac2d-8f56-49b5-9c9c-715807521468)

**Comment by kvarenzn** [comment]
你好，首先很遗憾地告诉你，时间要是对不准的话最受影响的就是红键，红键的判定是最复杂的，所以受时间偏移影响最大
rr这首曲子由于之前有人开过issue，因此我特意验证过，AT可以AP，规划算法是没有问题的，详见issue #74 
你可以使用微调功能对齐一下，然后再试试，不行再说

顺便一提，之前有个人，系统也是ColorOS 13，也是粉键miss，所以如果对齐了还是不行的话，没准还真是系统的问题

**Comment by kvarenzn** [comment]
忘了说了，我在测试的时候Rr的AT用的算法是**保守算法**，你也可以换个算法试一下，没准能成呢

**Comment by 364hao** [comment]
非常抱歉回复晚了，但是有个不好的消息（
我分别试了我能有的三台手机，除了刚刚的OPPOK10，还有HUAWEI畅想10，VIVO_Y83A，全部按我能做到的都对准了音，但没有一个能过的）

https://github.com/kvarenzn/phisap/assets/129530250/a46d0882-acb7-4c3f-92b4-2ef66f0659a5

https://github.com/kvarenzn/phisap/assets/129530250/6b0c4ad6-e7c5-4b42-a358-57df7c748eba

另一个vivo手机太慢了录不了屏就没有演示视频了，但与上面视频是一种情况。
此外，我曾经尝试过Rr的保守算法但是不知为何之前Phisap能规划的，现在却不能了
![Snipaste_2023-07-15_20-47-01](https://github.com/kvarenzn/phisap/assets/129530250/9a76d3f3-d144-42e0-be11-b16c21ba132b)
![Snipaste_2023-07-15_20-57-58](https://github.com/kvarenzn/phisap/assets/129530250/ce5c9d90-c24b-437d-a154-0d1fac940aec)
最后感谢作者的关注

**Comment by 364hao** [comment]
HUAWEI的手机系统是HarmonyOS2.0
Vivo的FuntouchOS，Android版本8.1.0

**Comment by kvarenzn** [comment]
感谢你提供的详尽的信息！那么我再回去测试一下

**Comment by 364hao** [comment]
是的

**Comment by 364hao** [comment]
> 至于漏红键的问题，我刚刚又测试了一下，激进算法也能AP（），emmm

（坏了，我买的手机都是断触的吗）

**Comment by kvarenzn** [comment]
很抱歉，我这边用模拟器也没复现成功红键断触，我也没有华为或是OPPO设备（倒是有台一加，可惜也不miss（））
所以只能请你来帮助我进行测试
我刚才缩减了一下flick的滑动时间（由原来的60ms减少到了30ms），请你更新一下代码，然后再试试，看看情况是否有改善？

**Comment by 364hao** [comment]
好的

**Comment by 364hao** [comment]
NICE!!!渡劫成功。太感谢作者了！谢谢！
![Screenshot_2023-07-15-21-42-43-32_a1b0c65cc4fc256422e0788e5ad09ca0](https://github.com/kvarenzn/phisap/assets/129530250/5883891a-cb1b-461d-acfe-ab0fd9749e8e)

**Comment by 364hao** [comment]
最后感谢一局：祝Phisap越做越精美吧，十分感谢啦！

**Comment by 364hao** [comment]
最后补充一句：新UI真的好看，并且也很实用！祝Phisap越来越完美

**Comment by kvarenzn** [comment]
> 最后补充一句：新UI真的好看，并且也很实用！祝Phisap越来越完美

谢谢！
