### ISSUE TITLE
无法AP你真惨AT

### ISSUE THREAD

**Issue by 364hao** [kvarenzn/phisap#84]
作者好，手机仍然是OPPO,系统是ColorOS13。操作系统为Windows11。Phisap版本为0.9，在You are the MiserableAT中激进和保守算法均无法AP

https://github.com/kvarenzn/phisap/assets/129530250/590c86b0-ab1e-491c-9eec-7d77531d053f

看起来像是4个长条结束后多点了一下，提前点到了上方的蓝键才FC了的，最终整个谱面1Good
至于保守算法就更惨了

https://github.com/kvarenzn/phisap/assets/129530250/6eda3681-c74c-45a3-823b-f01e0a32adb4

它时点时不点，我在谱面开头看不出时间是否对齐，没有微调时间，直到分数为88300多的时候才看到出来。应该是对的差不多的。但是好像该算法仍然有很多问题
此外，昨天更新，修复保守算法前，You are the MiserableAT与Rrhar'ilAT一样，无法用保守算法规划。
因此，我用保守算法尝试了一遍Rrhar'ilAT

https://github.com/kvarenzn/phisap/assets/129530250/d0a4e5d5-a29d-4faa-b25b-51da16baddf1

也是一样有很多说不出来的神奇操作
然后我换了Vivo手机试了一下，同样是这一种情况
我又尝试了旧版Phisap，与上面情况完全相同的。所以AP不了你真惨,就....挺离谱的
Phigros为3.1.1版本
值得一提的是，我所用过的Phisap的版本好像所有的保守算法都有此问题
![Snipaste_2023-07-16_08-25-04](https://github.com/kvarenzn/phisap/assets/129530250/d2d5c338-c333-4811-ae1a-5c619eebcbf0)
另外，似乎在每次Phisap启动后，自动打歌中途手动终止打歌进程，下一次再进行打歌时，手机并不会进行触控，即Phisap的打歌指令好像无效了（或scrcpy发送失败？）。无论用哪种算法都一样，我无法用视频或图片展示这一现象，在此抱歉。这种时候只能关闭Phisap的图形化界面再重启。
上面那张图片是上述情况后不重启Phisap，而点击“刷新”按钮出现的情况。

写的很长，是我目前为止遇到的问题的一部分，感谢作者耐心地阅读

**Comment by 364hao** [comment]
> 另外，似乎在每次Phisap启动后，自动打歌中途手动终止打歌进程，下一次再进行打歌时，手机并不会进行触控，即Phisap的打歌指令好像无效了（或scrcpy发送失败？）。无论用哪种算法都一样，我无法用视频或图片展示这一现象，在此抱歉。这种时候只能关闭Phisap的图形化界面再重启。

哦对，貌似不止手动终止，在打歌线程自动结束后，有时也会有这样的问题，包括但不限于课题模式

**Comment by kvarenzn** [comment]
我刚才用激进算法测试了一下，可惜还是没能复现成功（

OK，逐条回复

> 看起来像是4个长条结束后多点了一下，提前点到了上方的蓝键才FC了的，最终整个谱面1Good

有点奇怪，看起来四个长条之前你的时间对得还挺准，可是之后怎么就有点滞后了呢。应该是这里的问题导致的。我猜测应该是手机的硬件配置问题？phisap对设备的硬件要求挺玄学的，毕竟要在打歌的时候同时干三件事：运行phigros，处理触控事件以及编码视频，可能是算力不足导致的偏移问题？
你介意贴一下你的手机型号吗

> 至于保守算法就更惨了

测试了一下，保守算法确实崩了，下次修复吧

> 我又尝试了旧版Phisap，与上面情况完全相同的。所以AP不了你真惨,就....挺离谱的

旧版phisap两个算法都能AP，这个我测试过的。如果旧版都AP不了，那...

> 另外，似乎在每次Phisap启动后，自动打歌中途手动终止打歌进程，下一次再进行打歌时，手机并不会进行触控，即Phisap的打歌指令好像无效了（或scrcpy发送失败？）。无论用哪种算法都一样，我无法用视频或图片展示这一现象，在此抱歉。这种时候只能关闭Phisap的图形化界面再重启。

我大概能明白你的意思。之前我也遇到过，当时认为是打完歌之后没有回收pointer导致的（你可以理解为手指没有抬起，仍然在屏幕上放着），在2022年7月左右就修复了，确实在我的设备上也没再出现类似的情况。不过既然你说还有类似的情况，那看来是需要在打歌之后重启adb了，由于我这没法复现你的问题，所以下次更新之后还得看你的反馈

**Comment by 364hao** [comment]
![Screenshot_2023-07-16-09-29-59-20_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/kvarenzn/phisap/assets/129530250/62eddb37-3f3e-4ea4-a797-0d9bf2a20743)

**Comment by 364hao** [comment]
这个手机玩Phigros不会卡

**Comment by 364hao** [comment]
> 由于我这没法复现你的问题，所以下次更新之后还得看你的反馈

https://github.com/kvarenzn/phisap/assets/129530250/8017dbbb-b662-4626-86c0-97497c5e78a8
手机和电脑的视频稍微有点不同步，但大概就是这个样子

**Comment by 364hao** [comment]
> 我猜测应该是手机的硬件配置问题？phisap对设备的硬件要求挺玄学的，毕竟要在打歌的时候同时干三件事：运行phigros，处理触控事件以及编码视频，可能是算力不足导致的偏移问题？

我没开录屏试了一下，确实会滞后，但是之后就没有滞后了

**Comment by kvarenzn** [comment]
推了个更新，修复了保守算法规划的问题，另外缩短了滑键滑动的距离
你看看是否能解决你的问题

**Comment by 364hao** [comment]
emm，很抱歉两种算法与上面视频情况仍然完全一致

**Comment by kvarenzn** [comment]
> emm，很抱歉两种算法与上面视频情况仍然完全一致

请问Rr的一开始还是会漏三个长蓝条吗？

**Comment by 364hao** [comment]
是的

**Comment by kvarenzn** [comment]
emmm我现在也没啥头绪

我需要请你帮我个忙
你进入开发者模式，把“指针位置”这个选项打开（如下图，在你的设备上可能不是叫这个名字，反正意思差不多）
![Screenshot_20230716-171443](https://github.com/kvarenzn/phisap/assets/12197126/4dbc55ff-b98e-456a-8c4c-03971ac709f6)
然后再开着phisap录个屏，Rr的AT的开头部分就行（需要录到漏掉长蓝条那里），我再看看到底是什么问题

**Comment by 364hao** [comment]
https://github.com/kvarenzn/phisap/assets/129530250/f4644656-d048-4b0d-bee5-6e2c5339be50

**Comment by kvarenzn** [comment]
多谢

**Comment by 364hao** [comment]
？我怎么记得我删掉了片尾的啊，不过这指针位置选项开着有点卡，可能不是很清晰

**Comment by kvarenzn** [comment]
指针位置开着都卡，不过已经能看出问题了
三个长蓝条那里很明显触控指令没发出去，否则应该每一个长蓝条底下都有一个触点

**Comment by 364hao** [comment]
emm，所以我应该怎么做？

**Comment by kvarenzn** [comment]
暂时不需要你来帮我做什么了，我再想想办法
等着下次更新吧

**Comment by 364hao** [comment]
另外，scrcpy2.1版本似乎更新了禁用视频的选项，不知道是不是（机翻的），不过我用命令行启动了好像还真没有视频
![Snipaste_2023-07-18_15-47-07](https://github.com/kvarenzn/phisap/assets/129530250/124ef7d2-6a83-4de5-a788-4cfe4e43e7e0)

**Comment by kvarenzn** [comment]
> 确实，你真惨（，更新到0.11版本后，已经删除.cache.d文件夹了，没有勾选使用缓存按钮，保守算法还是一样，激进算法甚至bad的了），要不这歌咱先放放，反正不影响rks，看着更新里的更改我都心疼233

0.11的更新内容是早就想做得了，不然缓存太占地
另外，0.11这次更新没有改动算法相关的内容，因为我这边想了很多办法尝试复现你遇到的问题，可惜是每次都能AP（，所以就没动了

> 另外，scrcpy2.1版本似乎更新了禁用视频的选项，不知道是不是（机翻的），不过我用命令行启动了好像还真没有视频

2.0就能禁用视频，但是必须得开音频传输（2.1也是）。但音频传输不支持安卓10，我的手机就是安卓10，所以就没适配

**Comment by kvarenzn** [comment]
你遇到的问题还有一种可能的解释，就是触控事件在传输的过程中丢了（或者是你的设备不支持精度为1ms的触控事件发送？），下次更新就降低一下事件发送的频率（或是给最小精度加个设置）

**Comment by kvarenzn** [comment]
这回把采样率降了，看看问题解决没

**Comment by 364hao** [comment]
好的

**Comment by 364hao** [comment]
作者天才啊！
![Screenshot_2023-07-19-06-40-49-44_a1b0c65cc4fc256422e0788e5ad09ca0](https://github.com/kvarenzn/phisap/assets/129530250/4374f564-d16f-41b7-9bb4-04010b0dc229)
有生之年第一次用保守算法收歌

**Comment by 364hao** [comment]
让我再试试激进算法

**Comment by 364hao** [comment]
好吧，那个蓝了的蓝键可以过了，但红键却有问题了，应该只是我红键配置不对，理论上是可以ap的吧

**Comment by 364hao** [comment]
不过既然有一个算法可以ap那就足够了，感谢作者！(我再去找找有没有歌不能ap.jpg)

**Comment by 364hao** [comment]
红键的配置是：
滑键开始于: -17
滑键结束于: 17
滑动方向: 垂直于判定线
已经关闭通知栏下拉，在红键短纵时出现

**Comment by kvarenzn** [comment]
好
