### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by 233576** [kvarenzn/phisap#85]
报错信息：
Traceback (most recent call last):
  File "F:\phisap-main\main.py", line 30, in <module>
    from control import DeviceController
  File "F:\phisap-main\control.py", line 11, in <module>
    from algo.algo_base import TouchAction
  File "F:\phisap-main\algo\algo_base.py", line 2, in <module>
    from typing import Self
ImportError: cannot import name 'Self' from 'typing' (C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\typing.py)

python版本3.11和3.10都试过 系统win7

**Comment by kvarenzn** [comment]
看一下README吧
> 0. 请安装 Python 3.11

另外，我比较好奇你是怎么在win7上装上python 3.10的，不是只有win8及以上才能装3.10么

**Comment by 233576** [comment]
好的，有空用11试下
https://blog.csdn.net/weixin_45454897/article/details/129333857［Windows 7 下安装 python 3.9 及以上版本的方法（Anaconda 中的 python 版本还是 3.8 或以下 并且升级不了）_python3.9 win7_小黑°的博客-CSDN博客］

**Comment by kvarenzn** [comment]
> 另外这是win7装3.10的方法、、

手边没有装win7的电脑，没法测试。不过大致看了一眼，装法挺玄学的。据说是python 3.10开始用了一些win7没有的api，而且貌似win7没有高精度的时钟，所以我不敢保证phisap能在win7上正常工作。
不过也没关系，反正你遇到问题了就再开issue，我看看能不能解决

**Comment by 233576** [comment]
感谢感谢，重装了python311删掉了310，启动正常了
![无标题](https://github.com/kvarenzn/phisap/assets/139670248/d94404f8-2ba1-467d-8e82-eb5229a232f2)
