### ISSUE TITLE
BurnIN无法AP

### ISSUE THREAD

**Issue by 364hao** [kvarenzn/phisap#88]
又找到一个（，Phisap0.13，还是OPPO手机，红键配置为下：滑键开始于: -17，滑键结束于: 17，滑动方向: 平行于判定线。关闭手势，等，两种算法都试过了，这个是激进算法

https://github.com/kvarenzn/phisap/assets/129530250/b19e7783-da6e-47d2-baa8-38924606e5b3

很怪，看着有点像谱面对不上的感觉

https://github.com/kvarenzn/phisap/assets/129530250/d71d0041-e5bc-4570-a094-7f4b349b8e67

我开了指针位置，也情况差不多，Windows11，Phigros3.1.1，暂时没有测试其他手机
不过神奇的是，旧版Phisap居然能打
![Screenshot_2023-07-19-15-48-44-98_a1b0c65cc4fc256422e0788e5ad09ca0](https://github.com/kvarenzn/phisap/assets/129530250/1a64dc85-2307-4379-9235-7ab94df25d9a)
但是激进算法开头会爆一个bad，重复了好几遍也一样，旧版保守算法用都用不了
所以，BurnIN无法AP啦，又得麻烦大佬查查bug惹）

**Comment by 364hao** [comment]
今天发现保守算法无法规划DistortedFateAT了，
![Snipaste_2023-07-20_15-17-59](https://github.com/kvarenzn/phisap/assets/129530250/fa7fadad-71b1-478a-aa4f-9897d01a1e61)

**Comment by 364hao** [comment]
话说Phisap0.13版本的激进算法好难用啊（，课题模式DistortedFateAT老是漏几个红键或蓝键

**Comment by 364hao** [comment]
好了又发现一个),保守算法好容易崩啊（恼）
![Snipaste_2023-07-20_15-52-02](https://github.com/kvarenzn/phisap/assets/129530250/3184e738-f942-425a-a13d-1ac614d343ca)

**Comment by 364hao** [comment]
![Snipaste_2023-07-20_15-57-42](https://github.com/kvarenzn/phisap/assets/129530250/727944ea-f071-4e61-ac75-f471c8ca3848)
好像都是一个问题

**Comment by 364hao** [comment]
不过不得不说的是，新的保守算法能规划的真的很好用！比激进算法稳定的太多了，希望能支持更多谱面！

**Comment by 364hao** [comment]
首先为我私自修改程序保守算法抱歉，但是呢，我发现在删去保守算法的82行，并将303行的pointers_count改为10后，保守算法便能正常规划，且我测试了狂喜籣舞的AT难度可以AP，目前来说是个临时解决办法

**Comment by 364hao** [comment]
收回我的话（悲

**Comment by kvarenzn** [comment]
我测，现在连bga都无法规划么，我知道了

另外，虽然偏题了，我还是想提一句，phisap以`WTFPL`协议开源，也就是说任何人可以以任何目的使用或修改phisap
亦即`You just DO WHAT THE FUCK YOU WANT TO.`

**Comment by 364hao** [comment]
感谢！

**Comment by 364hao** [comment]
更新了下，BurnIN两个算法仍有上面的问题

**Comment by 364hao** [comment]
![Snipaste_2023-07-26_17-19-32](https://github.com/kvarenzn/phisap/assets/129530250/a6b6d986-0fe5-48ab-9124-6e970b14c75c)
![Snipaste_2023-07-26_17-19-55](https://github.com/kvarenzn/phisap/assets/129530250/59d8a3ea-e980-4636-abc2-556573c58b21)
BGA还是无法规划.jpg，顺便这是我手机的屏幕触控率

**Comment by 364hao** [comment]
不好意思看错了，更新的是激进算法，让我再测试下

**Comment by 364hao** [comment]
![Screenshot_2023-07-26-18-12-10-66_a1b0c65cc4fc256422e0788e5ad09ca0](https://github.com/kvarenzn/phisap/assets/129530250/66242af2-4826-445b-8687-855d0d77e039)
就...挺离谱的，前两首歌保证计时器同步到位了，却会爆GOOD，都是有红键在触发时爆的，不知道什么原因
顺便，两首歌算法为激进算法，保守算法规划不了
Rr那边情况我是用保守算法的，出现了之前issue的情况
[https://github.com/kvarenzn/phisap/issues/84](url)

> 另外，似乎在每次Phisap启动后，自动打歌中途手动终止打歌进程，下一次再进行打歌时，手机并不会进行触控，即Phisap的打歌指令好像无效了（或scrcpy发送失败？）。无论用哪种算法都一样，我无法用视频或图片展示这一现象，在此抱歉。这种时候只能关闭Phisap的图形化界面再重启。
> 上面那张图片是上述情况后不重启Phisap，而点击“刷新”按钮出现的情况。
不过我发现只要你把一根手指放在屏幕上，Phisap就能打歌了，挺神奇的（但我没有打完）
好像有点偏题.png

**Comment by 364hao** [comment]
> 前两首歌保证计时器同步到位了，却会爆GOOD，都是有红键在触发时爆的，不知道什么原因

不不不，应该不是红键的问题
![Snipaste_2023-07-26_18-24-35](https://github.com/kvarenzn/phisap/assets/129530250/baee29b1-faaa-457d-b9b7-4e90464c28a7)
我的手机突然卡了一下，然后就爆g了，接着看电脑cmd的控制台应该刚好就是这时出现的，虽然这应该是视频编码的问题
不过，之前爆g的情况手机到没有卡顿，但似乎有这类error输出
其实很久之前就有这种情况了

**Comment by kvarenzn** [comment]
> 我的手机突然卡了一下，然后就爆g了，接着看电脑cmd的控制台应该刚好就是这时出现的，虽然这应该是视频编码的问题

如果是电脑端报的错则一般是以`[client]`开头，或者没有前缀，比如那行`error while decoding MB 88 41, bytestream -9`，这类错误是可以忽略的
而你截图中红箭头指的位置的这个错实际上是手机报的(scrcpy的服务端，有`[server]`前缀)，所以**不能忽略**。那么就回到了那个老问题上，请问当你使用scrcpy的时候有没有类似的报错？

**Comment by kvarenzn** [comment]
这个补充信息还是挺重要的（所以你为啥不早说

**Comment by 364hao** [comment]
> 你的这个补充信息还是挺重要的（所以你为啥不早说

因为我一直以为是我的问题www

**Comment by 364hao** [comment]
让我去看看

**Comment by kvarenzn** [comment]
> 因为我一直以为是我的问题www

啊这，不过现在发现也不晚

**Comment by 364hao** [comment]
![Snipaste_2023-07-26_18-43-28](https://github.com/kvarenzn/phisap/assets/129530250/a372703d-7834-44b9-bf08-7447131af971)

**Comment by 364hao** [comment]
另外这个成绩是刚刚打的

**Comment by 364hao** [comment]
我采用了之前修复远古版Phisap不能在这台手机上运行的方法，在control.py中加入了'max_size=1920',

**Comment by 364hao** [comment]
不过DF还是一样爆，Iga是我开头计时器没对齐（，后面好像没爆good了，Rr是我用保守算法打的，全程按着屏幕，应该是手出汗了miss了吧

**Comment by 364hao** [comment]
测试的scrcpy版本为2.0

**Comment by kvarenzn** [comment]
看来scrcpy也有

> 我采用了之前修复远古版Phisap不能在这台手机上运行的方法，在control.py中加入了'max_size=1920',

这个办法有用吗，理论上应该是没啥效果的，因为scrcpy会自动发现合适的屏幕尺寸

> 全程按着屏幕，应该是手出汗了miss了吧

为啥要按着屏幕（

> 测试的scrcpy版本为2.0

（要不你再试试scrcpy 2.1，据说有修复类似问题，如果2.1版本能行的话那么下次更新我将适配scrcpy-server-v2.1

**Comment by kvarenzn** [comment]
顺便，如果方便的话，请发一下命令
```powershell
scrcpy --list-encoders
```
的运行结果

**Comment by kvarenzn** [comment]
或许换一个编码器可能会好点

**Comment by 364hao** [comment]
![Snipaste_2023-07-26_18-52-01](https://github.com/kvarenzn/phisap/assets/129530250/f937cdac-3be0-4f7a-8a01-b74909b60dd2)

**Comment by 364hao** [comment]
> （要不你再试试scrcpy 2.1，据说有修复类似问题，如果2.1版本能行的话那么下次更新我将适配scrcpy-server-v2.1

![Snipaste_2023-07-26_18-53-26](https://github.com/kvarenzn/phisap/assets/129530250/daee8cfb-a76c-47a3-8187-6c6700444f1c)
好像不行（

**Comment by 364hao** [comment]
![Snipaste_2023-07-26_18-54-27](https://github.com/kvarenzn/phisap/assets/129530250/179ae418-2671-410c-973a-32a383a11db6)
这是2.1的

**Comment by 364hao** [comment]
scrcpy2.1.1也一样
![Snipaste_2023-07-26_18-56-31](https://github.com/kvarenzn/phisap/assets/129530250/b20493e1-bfdc-41b1-9059-0d0048a51d8f)

**Comment by kvarenzn** [comment]
> 按着屏幕有效果，我在上面说了

好吧，我的问题。不过虽然你这个方法虽然很有创意，但是百分百会爆g，我再看看有没有别的解决办法

> 好像不行（

emmm，加个参数设置一下解码器呢？比如下面这个
```powershell
scrcpy.exe --video-codec=h264 --video-encoder=c2.android.avc.encoder
```
或者这个
```powershell
scrcpy.exe --video-codec=h264 --video-encoder=OMX.google.h264.encoder
```

**Comment by 364hao** [comment]
![Snipaste_2023-07-26_19-00-44](https://github.com/kvarenzn/phisap/assets/129530250/ef539b1a-b697-4a25-b527-ca837e4d8448)

**Comment by 364hao** [comment]
貌似没了

**Comment by kvarenzn** [comment]
好

**Comment by 364hao** [comment]
![Snipaste_2023-07-26_19-01-37](https://github.com/kvarenzn/phisap/assets/129530250/f5306316-d529-42a0-98cd-72a6e0b1f82a)
这个也可以

**Comment by kvarenzn** [comment]
那看来问题出在默认视频编码器上了
我一会推个更新，你看看phisap到时候能不能正常工作

**Comment by 364hao** [comment]
OK

**Comment by kvarenzn** [comment]
OK推了，看看效果如何

**Comment by 364hao** [comment]
好

**Comment by ghost** [comment]
暂时没报错
![Snipaste_2023-07-26_19-15-45](https://github.com/kvarenzn/phisap/assets/129530250/bcc4f309-ba05-4ed0-87dd-cd4a19f1bf3f)

**Comment by ghost** [comment]
emm，只测试了DFAT课题模式，这次蓝的时候没有弹出[server]error的报错，但是手机却谜之卡了一下，比如音频一下延长了一会，后面计时器就对不准了

**Comment by ghost** [comment]
![Snipaste_2023-07-26_19-20-45](https://github.com/kvarenzn/phisap/assets/129530250/5a27f63d-4c7b-48cf-9b05-0e079779c962)

**Comment by 364hao** [comment]
歌没打完

**Comment by 364hao** [comment]
就......很离谱

**Comment by ghost** [comment]
额，测试了下Phisap0.8版本，也是2good性了

**Comment by ghost** [comment]
不行我要笑死了哈哈哈，我拿手头上所有版本的Phisap测试没有一个AP的，又拿刚更新的版本发现本来+20ms的偏移后面越来越小到-60ms的偏移了

**Comment by ghost** [comment]
应该是手机的问题

**Comment by 364hao** [comment]
偏题了吧（

**Comment by ghost** [comment]
不过呢，我用旧版PhisapAP了
![Snipaste_2023-07-26_19-47-57](https://github.com/kvarenzn/phisap/assets/129530250/b2ad5e64-7b31-4221-9d91-13a8d711b940)
![Snipaste_2023-07-26_19-47-24](https://github.com/kvarenzn/phisap/assets/129530250/8d6f8ab4-5691-45e1-b50b-04118aafa2c7)

**Comment by 364hao** [comment]
我记得好像把旧版的algo1找新版改了改采样率

**Comment by 364hao** [comment]
不过呢，这个issue问题解决了，可以关了

**Comment by 364hao** [comment]
感谢作者啦

**Comment by kvarenzn** [comment]
别急，先开着吧，我这边也在改进算法，等到彻底能在你的设备上AP了再关也不迟

**Comment by 364hao** [comment]
哦对，测试了下，旧版phisap小修小改可以课题模式ap铁人三项了，只不过我手残，老是开头就蓝了～(￣▽￣～)~

**Comment by ghost** [comment]
![Snipaste_2023-07-27_16-19-02](https://github.com/kvarenzn/phisap/assets/129530250/dca4445c-06bf-42cd-8a51-93e496f7a825)
凹了好久，用的旧版Phisap，感觉旧版十分的稳定，就是好难对齐啊啊啊

**Comment by ghost** [comment]
问下，现在开issue应该用dev版还是stable版，如果是stable版我这个issue是不是可以关了.png

**Comment by kvarenzn** [comment]
都可以，只要开issue时注明版本就行

**Comment by ghost** [comment]
好的好的

**Comment by kvarenzn** [comment]
直到昨天我试了一下才知道，Burn的IN无法AP跟算法没关系
是特么的我谱面解析代码写错了
Burn的IN居然是旧谱格式，然后我上次适配RPE和PEC的时候只适配了新的官谱格式，旧格式就没再管过了
所以用旧版phisap就可以AP
这个将尽快修复

**Comment by 364hao** [comment]
az

**Comment by ghost** [comment]
![Screenshot_2023-08-06-15-15-48-75_a1b0c65cc4fc256422e0788e5ad09ca0](https://github.com/kvarenzn/phisap/assets/129530250/42afc6c2-97d6-42d8-a53c-f4142cb8b79e)
好耶
