### ISSUE TITLE
UI问题

### ISSUE THREAD

**Issue by ShintoKosei** [kvarenzn/phisap#94]
这实际界面UI与图片UI有问题啊（故意找茬，咱也不知道是不是打开方式不正确(? ）
![%7B78CF0689-9861-446e-8824-B418BC23DB25%7D](https://github.com/kvarenzn/phisap/assets/67397639/d074ec07-bcfa-42b8-91d2-f735b83e654b)

**Comment by kvarenzn** [comment]
README中的截图截自于archlinux上运行的phisap，GTK主题为Materia Dark。我将在README中加入补充信息

由于Qt在每种系统上的样式都不相同，所以只要布局和文字和README中的一致就行
