### ISSUE TITLE
游玩stasis AT难度时漏打

### ISSUE THREAD

**Issue by zzy6011** [kvarenzn/phisap#96]
![image](https://github.com/kvarenzn/phisap/assets/117558117/ec9061f4-ff61-4d30-8ec9-7c9b9b8a7018)
如图，这两个长条会漏掉不接，两个算法都试过，说实话感觉新版本的phisap小问题好多（

**Comment by kvarenzn** [comment]
请问“漏掉不接”是指？
- 整根长条直接miss，连起始部分也没点到
- 长条的起始部分点到了，中间断了

**Comment by zzy6011** [comment]
整个长条是断的，因为这里面塞了黄键还有闪烁特效所以看不清长条的起始部分，中间一部分黄健也是漏了的，怀疑是特效的问题，因为前面5k段这个地方也有时候会断
![image](https://github.com/kvarenzn/phisap/assets/117558117/b88215a0-2a20-4747-ab2c-3c94a41c52be)
如图这一串黄健前的双压，右边那个有时候会miss或good，这一串黄健有着抖动的特效，盲猜是因为这个卡了所以g或miss（（

**Comment by zzy6011** [comment]
顺带一提，用的最新版phisap

**Comment by zzy6011** [comment]
你说得对，但是在DESTRUCTION 3,2,1 AT中600combo那个红也会漏掉，666两个长条也和stasis一样漏掉，在打歌过程中有事会卡顿掉帧导致late，miss，bad（我设备性能太差？

**Comment by zzy6011** [comment]
666combo

**Comment by zzy6011** [comment]
我靠用老版本的phisap可以ap上面两个新版本不能p的曲子
![image](https://github.com/kvarenzn/phisap/assets/117558117/0296fd01-2649-48f0-90f3-8969e00832d4)
老版本的不会卡顿，新版本老是掉帧（（我设备的问题吗（

**Comment by Eternity231** [comment]
掉帧的话建议每次打完重开一次程序，不然一直不重开最后会卡爆

**Comment by zzy6011** [comment]
我是打完一次必须重开，不然第二首就会没反应。掉帧卡顿确实是新版本出现的，旧版本没有过（（

**Comment by Eternity231** [comment]
我去试了一下，stasis长条掉的但是321可以接上
