### ISSUE TITLE
无法连接设备

### ISSUE THREAD

**Issue by Solitrek** [kvarenzn/phisap#99]
最近换了台电脑，win11，但是phisap没法用了，搜了半天也不知道怎么修
![Screenshot 2023-07-31 012805](https://github.com/kvarenzn/phisap/assets/131033196/469d080b-3e44-490c-a0e5-ed23e7428b31)

**Comment by ghost** [comment]
这个应该不是Phisap的问题，如果adb devices命令获取不到设备的话Phisap也不行，可以试试有线调试adb（或许还种情况adb环境没配置好）

**Comment by Solitrek** [comment]
解决了
